const STR = {
cs: {
  app_name:'NutriLog',
  nav_today:'Dnes', nav_log:'Deník', nav_suggest:'Návrhy', nav_chat:'Chat', nav_review:'Přehled',
  t_today:'Dnes', t_log:'Deník', t_suggest:'Návrhy', t_chat:'Chat', t_review:'Přehled',
  t_profile:'Profil', t_settings:'Nastavení',
  back:'Zpět', close:'Zavřít', save:'Uložit', cancel:'Zrušit', confirm:'Potvrdit',
  yes:'Ano', no:'Ne', open_settings:'Nastavení', loading:'Načítám',

  /* Today */
  today_intro:'Osobní deník jídla a živin.',
  today_noprofile_h:'Začněte profilem',
  today_noprofile_p:'Bez profilu nelze spočítat nic. Vyplnění zabere asi tři minuty a kdykoli se dá změnit.',
  today_setup_btn:'Vyplnit profil',
  energy_eyebrow:'Odhad denní energie',
  range_to:'až',
  kcal:'kcal',
  per_day:'na den',
  why_range_btn:'Proč je to rozsah a ne číslo',
  floor_binding:'Spodní hranici drží podlaha, ne výpočet.',
  floor_short:'Podlaha',
  macro_p:'Bílkoviny', macro_f:'Tuky', macro_c:'Sacharidy',
  grams:'g',
  protein_per_kg:'{a} až {b} g na kg váhy',
  protein_low_note:'Spodní konec rozsahu bílkovin je nízký. Při hubnutí se obvykle doporučuje aspoň 1,2 g na kg váhy.',
  protein_high_note:'Horní konec rozsahu bílkovin je vysoký. Nad zhruba 2,2 g na kg váhy už další přínos není prokázaný.',
  profile_card_h:'Váš profil',
  profile_edit:'Upravit',
  profile_summary:'{sex}, {age} let, {height} cm, {weight} kg',
  dir_short_lose:'pomalu hubnout', dir_short_maintain:'držet váhu', dir_short_gain:'pomalu přibírat',
  today_phase_note:'Ve fázi 1 umí aplikace profil, cíle, zálohu a nastavení. Zapisování jídla přijde ve fázi 2.',
  targets_h:'Denní cíle',
  recompute_note:'Cíle se přepočítají po každé změně profilu.',

  /* Why a range */
  wr_title:'Proč je to rozsah a ne číslo',
  wr_intro:'Ten rozsah není opatrnost. Je to poctivá šíře toho, co se z vašich údajů dá spočítat.',
  wr_r1:'Rovnice (Mifflin, St Jeor) byla sestavena na skupinách lidí, ne na vás. U jednotlivce se typicky mýlí zhruba o desetinu nahoru nebo dolů, občas víc.',
  wr_r2:'Odhad aktivity je největší zdroj chyby. Dva lidé, kteří svůj týden popíší úplně stejně, se můžou lišit o několik set kcal denně.',
  wr_r3:'Rovnice nezná složení vašeho těla. Více svalů zvyšuje klidový výdej, více tuku ho na kilogram snižuje.',
  wr_r4:'Čísla na obalech jsou také jen odhad. Evropská pravidla pro označování připouštějí u energie rozdíl až kolem pětiny oproti tomu, co je v balení.',
  wr_r5:'Nemoc, spánek, chlad, léky a menstruační cyklus mění denní výdej ze dne na den.',
  wr_math_h:'Jak je rozsah spočítaný',
  wr_math_p:'Klidový výdej podle rovnice: asi {rmr} kcal. Vynásobeno pásmem aktivity: asi {tdee} kcal. Dvě nezávislé nejistoty (rovnice a aktivita) se skládají odmocninou ze součtu čtverců, ne prostým sčítáním; vychází z toho {pct} % na každou stranu. Nakonec se přičte nebo odečte úprava podle zvoleného směru.',
  wr_fix_h:'Co rozsah zúží',
  wr_fix_p:'Jediná spolehlivá cesta je vaše vlastní váha v čase. Když se dva až tři týdny jí kolem stejné hodnoty a váha se drží, je ta hodnota vaším skutečným výdejem a rovnice se dá odložit. Sledování váhy v čase přijde v další fázi.',
  wr_floor_h:'Co je podlaha',
  wr_floor_p:'Aplikace nikdy nenavrhne cíl pod {floor} kcal. Ta hodnota je vyšší z dvou: váš odhadovaný klidový výdej ({rmr} kcal) a pevné minimum {abs} kcal. Pod klidovým výdejem tělo dlouhodobě šetří jinde: energií, spánkem, náladou a svalovou hmotou.',
  wr_notmed:'Toto není lékařská rada. Pokud máte onemocnění nebo berete léky, které ovlivňují váhu, chuť k jídlu nebo trávení, proberte cíle s lékařem.',

  /* Later phases */
  phase2:'Fáze 2', phase3:'Fáze 3', phase4:'Fáze 4',
  soon_log_h:'Zapisování jídla',
  soon_log_p:'Vyhledání v databázi potravin, čtení čárových kódů a etiket, ruční zadání. Každé číslo si ponese svůj zdroj.',
  soon_suggest_h:'Návrhy jídel',
  soon_suggest_p:'Návrhy podle vašeho profilu, vybavení, času a rozpočtu. Alergie a věci, které nejíte, budou tvrdý filtr.',
  soon_chat_h:'Otázky na suroviny',
  soon_chat_p:'Dotazy na suroviny a recepty, zodpovězené s ohledem na váš profil.',
  soon_review_h:'Týdenní a měsíční přehled',
  soon_review_p:'Souhrny za týden a měsíc. Odhadované hodnoty v nich budou označené jako odhady.',
  soon_nofake:'Tato obrazovka je záměrně prázdná. Nejsou tu vymyšlená data, aby nevypadala hotově dřív, než bude.',

  /* Profile */
  p_title:'Profil',
  p_intro:'Z těchto údajů se počítají cíle. Alergie a věci, které nejíte, budou platit všude v aplikaci.',
  p_basics:'Základní údaje',
  p_sex:'Pohlaví', p_male:'Muž', p_female:'Žena',
  p_sex_note:'Rovnice pro klidový výdej existuje jen ve dvou variantách, mužské a ženské. Vyberte tu, která se lépe blíží vaší fyziologii; ovlivní to výsledek zhruba o 150 kcal.',
  p_age:'Věk', p_years:'let',
  p_height:'Výška', p_cm:'cm',
  p_weight:'Současná váha', p_kg:'kg',
  p_direction:'Směr',
  dir_lose:'Pomalu hubnout', dir_lose_d:'Mírný deficit, zhruba desetina denního výdeje.',
  dir_maintain:'Držet váhu', dir_maintain_d:'Cíl se rovná odhadovanému výdeji.',
  dir_gain:'Pomalu přibírat', dir_gain_d:'Mírný přebytek, zhruba čtrnáctina denního výdeje.',
  p_activity:'Aktivita',
  p_activity_note:'Vyberte to, co skutečně popisuje běžný týden, ne ten nejlepší.',
  act1_t:'Převážně sedavý týden', act1_d:'Většinu dne sedím. Chůze po bytě a do obchodu, žádné plánované cvičení.',
  act2_t:'Trochu pohybu', act2_d:'Denně 30 až 60 minut chůze dohromady, nebo jeden až dva lehčí tréninky týdně.',
  act3_t:'Pravidelný pohyb', act3_d:'Tři až čtyři tréninky týdně, nebo práce, při které jsem půl dne na nohou.',
  act4_t:'Hodně pohybu', act4_d:'Tvrdý trénink pětkrát týdně a víc, nebo fyzicky náročná práce celý den.',
  p_macro:'Rozdělení živin',
  ms_balanced:'Vyvážené', ms_balanced_d:'25 % bílkoviny, 30 % tuky, 45 % sacharidy.',
  ms_protein:'Více bílkovin', ms_protein_d:'35 % bílkoviny, 30 % tuky, 35 % sacharidy.',
  ms_lowcarb:'Méně sacharidů', ms_lowcarb_d:'30 % bílkoviny, 45 % tuky, 25 % sacharidy.',
  ms_custom:'Vlastní', ms_custom_d:'Zadejte si procenta sami.',
  ms_sum:'Součet: {n} %',
  ms_sum_err:'Součet musí být 100 %.',
  p_allergy_h:'Alergie a co nejím',
  p_allergy_intro:'Alergie je tvrdý zákaz: taková surovina se nikdy neobjeví v návrhu, receptu ani v odpovědi chatu. „Nejím“ je vaše volba, aplikace ji bude respektovat stejně tvrdě.',
  p_allergy_common:'Časté alergeny podle přílohy II nařízení EU 1169/2011. Klepnutím přidáte:',
  p_item_ph:'Napište surovinu',
  p_add:'Přidat',
  p_type_allergy:'Alergie', p_type_refuse:'Nejím',
  p_synonyms:'Také se počítá jako',
  p_synonyms_ph:'další názvy, oddělené čárkou',
  p_syn_note:'Tyto názvy se použijí při kontrole surovin. Čím víc jich je, tím spolehlivější filtr.',
  p_allergy_none:'Zatím nic. To je v pořádku, dá se doplnit kdykoli.',
  p_remove:'Odebrat',
  p_cuisines:'Kuchyně, které mám rád',
  p_cuisine_free_ph:'Jiná kuchyně',
  p_time:'Kolik času mám na vaření',
  p_time_weekday:'Ve všední den', p_time_weekend:'O víkendu',
  tm1:'do 15 minut', tm2:'15 až 30 minut', tm3:'30 až 60 minut', tm4:'přes hodinu',
  p_equipment:'Vybavení kuchyně',
  eq_hob:'Varná deska', eq_oven:'Trouba', eq_micro:'Mikrovlnka', eq_blender:'Mixér',
  eq_airfryer:'Horkovzdušná fritéza', eq_pressure:'Tlakový hrnec', eq_none:'Nic z toho',
  p_budget:'Rozpočet na jídlo',
  p_budget_note:'Na týden, v korunách.',
  bud1:'do 1 000 Kč', bud2:'1 000 až 1 500 Kč', bud3:'1 500 až 2 500 Kč',
  bud4:'2 500 až 4 000 Kč', bud5:'přes 4 000 Kč', bud6:'Nesleduji',
  p_save:'Uložit profil',
  p_saved:'Profil uložen.',
  p_missing:'Chybí: {list}',
  p_required:'povinné',

  /* Settings */
  set_look:'Vzhled a jazyk',
  set_theme:'Motiv', th_device:'Podle telefonu', th_light:'Světlý', th_dark:'Tmavý',
  set_lang:'Jazyk',
  set_profile_h:'Profil a cíle',
  set_profile_open:'Otevřít profil',
  set_keys_h:'Klíče k API',
  set_keys_note:'Klíče se ukládají jen do tohoto telefonu. Nikdy neodcházejí do zálohy ani do exportu. Když telefon ztratíte, klíče zrušte u jejich vydavatele.',
  k_anthropic:'Anthropic API klíč',
  k_usda:'USDA FoodData Central klíč',
  k_github:'GitHub token pro zálohu',
  k_repo:'Repozitář pro zálohu',
  k_repo_ph:'uzivatel/nazev-repozitare',
  k_branch:'Větev',
  k_show:'Ukázat', k_hide:'Skrýt',
  test_btn:'Ověřit připojení',
  test_running:'Ověřuji...',
  test_need_key:'Nejdřív vyplňte klíč.',
  test_need_repo:'Nejdřív vyplňte klíč i repozitář ve tvaru uzivatel/nazev.',
  set_models_h:'Modely',
  m_chat:'Chat a návrhy', m_vision:'Čtení fotek a etiket', m_analysis:'Týdenní a měsíční rozbor',
  m_note:'Názvy modelů se časem mění. Tlačítko Ověřit připojení u klíče Anthropic zároveň zkontroluje, jestli tyto tři názvy pořád existují.',
  m_check_ok:'Všechny tři modely existují.',
  m_check_bad:'Tyto názvy modelů API nezná: {list}',
  set_price_h:'Ceny a útrata',
  price_in:'Vstup, USD za milion tokenů',
  price_out:'Výstup, USD za milion tokenů',
  price_note:'Předvyplněno z ceníku Anthropic k 9. srpnu 2026. Ceny se mění; ověřte si je a případně přepište.',
  price_intro_warn:'Sonnet 5 má do 31. srpna 2026 zaváděcí cenu 2 a 10 USD. Poté se má zvednout na 3 a 15 USD.',
  usage_h:'Spotřeba',
  usage_calls:'Volání API',
  usage_tokens_in:'Vstupní tokeny', usage_tokens_out:'Výstupní tokeny',
  usage_cost:'Odhad útraty',
  usage_zero:'Ve fázi 1 aplikace neposílá do modelu žádná data. Ověření připojení používá seznam modelů, což je zdarma. Proto je tu zatím nula.',
  usage_reset:'Vynulovat počítadlo',

  set_data_h:'Data a záloha',
  d_size:'Zabrané místo',
  d_persist:'Trvalé úložiště',
  d_persist_yes:'Ano, prohlížeč data sám nesmaže',
  d_persist_no:'Ne, prohlížeč může data při nedostatku místa smazat',
  d_unknown:'Neznámé',

  dg_h:'Co tenhle prohlížeč umí',
  dg_p:'Přečti si tohle, když něco nejde. Netýká se to tvých dat, jen toho, co prohlížeč v telefonu dovolí.',
  dg_mode:'Jak je aplikace spuštěná',
  dg_mode_app:'Jako aplikace, bez adresního řádku',
  dg_mode_tab:'Jako stránka v prohlížeči',
  dg_sw:'Práce bez internetu',
  dg_sw_on:'Zapnutá, stránka se načítá z telefonu',
  dg_sw_reg:'Připravená, projeví se po dalším otevření',
  dg_sw_fail:'Nepodařilo se zapnout',
  dg_sw_no:'Tenhle prohlížeč to neumí',
  dg_barcode:'Čtení čárových kódů (fáze 2)',
  dg_camera:'Přístup ke kameře (fáze 2)',
  dg_share:'Sdílení souboru z aplikace',
  dg_yes:'Ano',
  dg_no:'Ne',
  dg_engine:'Prohlížeč',
  dg_copy:'Zkopírovat tenhle výpis',
  dg_copied:'Zkopírováno. Vlož mi to do chatu.',
  dg_copyfail:'Kopírování nevyšlo. Označ text nahoře a zkopíruj ho ručně.',
  dg_note_tab:'Aplikace běží jako stránka v prohlížeči. Funguje celá, ale smazání dat prohlížeče ji vymaže. O to důležitější je záloha do repozitáře.',

  b_target:'Cíl zálohy',
  b_target_none:'Nenastaveno',
  b_last:'Poslední ověřená záloha',
  b_never:'Zatím nikdy',
  b_next:'Stav',
  b_state_idle:'Nečinné', b_state_pending:'Čeká na odeslání', b_state_running:'Odesílám',
  b_state_error:'Chyba', b_state_offline:'Bez připojení, zkusím to znovu',
  b_state_empty:'Zatím není co zálohovat',
  b_last_error:'Poslední chyba',
  b_run_now:'Zálohovat hned',
  b_export:'Ruční export',
  b_export_note:'Uloží soubor s datem do telefonu nebo ho pošle přes sdílení.',
  b_export_note_dl:'Tenhle prohlížeč neumí sdílení, takže se soubor uloží mezi stažené soubory v telefonu.',
  b_import:'Obnovit ze souboru',
  b_restore_cloud:'Obnovit z kopie v repozitáři',
  b_restore_warn:'Obnovení nahradí všechna data v telefonu obsahem zálohy. Co je v telefonu teď a není v záloze, zmizí.',
  b_snapshots_h:'Denní kopie v telefonu',
  b_snapshots_note:'Posledních sedm dní. Chrání před chybou v aplikaci, nechrání před smazáním dat prohlížeče.',
  b_snapshot_none:'Zatím žádné.',
  b_snapshot_restore:'Obnovit',
  b_secrets_note:'Záloha ani export nikdy neobsahují klíče k API. Na novém telefonu je zadáte znovu.',

  danger_h:'Nevratné',
  danger_p:'Smaže profil, cíle, denní kopie i klíče k API v tomto telefonu. Kopie v repozitáři zůstane.',
  danger_type:'Pro potvrzení napište {word}',
  danger_word:'SMAZAT',
  danger_btn:'Smazat všechna data',
  danger_done:'Data smazána.',

  about_h:'O aplikaci',
  about_version:'Verze',
  about_schema:'Formát dat',
  about_update:'Zkontrolovat aktualizaci',
  about_update_none:'Máte nejnovější verzi.',
  about_update_yes:'Nová verze stažena, aplikace se načte znovu.',
  about_install:'Nainstalovat do telefonu',
  about_clear_h:'Co smaže data',
  about_clear_p:'Když v prohlížeči smažete data pro tuto stránku, zmizí všechno, co není v záloze: profil, cíle i klíče. Proto existuje automatická záloha.',
  about_token_h:'Co dosáhne token',
  about_token_p:'Token pro zálohu má přístup jen k jednomu soukromému repozitáři, který jste zadali, a jen k obsahu souborů. Nemá přístup k ostatním repozitářům, k účtu ani k platbám. Když telefon ztratíte, zrušte ho v nastavení GitHubu.',
  about_revoke:'Zrušit token na GitHubu',

  /* backup bar */
  bar_unconf_new:'Automatická záloha zatím není nastavená. Nastavte ji dřív, než začnete zapisovat data.',
  bar_unconf_data:'Máte data a nemáte zálohu. Když smažete data prohlížeče, zmizí.',
  bar_stale:'Záloha se nepovedla už {h} hodin.',
  bar_setup:'Nastavit zálohu',
  bar_export:'Exportovat ručně',

  /* generic */
  err_prefix:'Chyba',
  err_offline:'Telefon je bez připojení.',
  ok:'Hotovo',
  copy:'Kopírovat',
  copied:'Zkopírováno.',
  n_a:'Není',
  cancelled:'Zrušeno.',
  restore_ok:'Data obnovena.',
  import_bad_file:'Tento soubor nevypadá jako záloha NutriLogu. Nic se nezměnilo.',
  import_bad_schema:'Tento soubor je z novější verze aplikace (formát {n}). Tahle verze ho neumí přečíst, tak ho radši nepoužila. Nic se nezměnilo.',
  backup_ok:'Záloha odeslána.',
  backup_same:'Beze změny, záloha je aktuální.',
  backup_empty:'Zatím není co zálohovat.',
  backup_fail:'Záloha se nepovedla.',
  repo_public_warn:'Pozor: tento repozitář je veřejný. Váš deník jídla by byl na internetu. Použijte soukromý.',
  repo_is_pages_warn:'Pozor: tohle je zřejmě stejný repozitář, ze kterého běží tahle aplikace. Záloha by se zveřejnila. Použijte jiný, soukromý.',
  repo_private_ok:'Repozitář je soukromý.',
  write_ok:'Zápis do repozitáře funguje.',
  write_fail:'Zápis do repozitáře nefunguje.',
  delete_fail:'Zkušební soubor se nepodařilo smazat, ale zápis funguje. Soubor nutrilog-write-test.txt můžete smazat ručně.',
  usda_ok:'USDA odpovědělo. Prohlížeč se k databázi dostane přímo, takže fáze 2 může stavět na tomhle.',
  anthropic_ok:'Klíč funguje. Modelů dostupných: {n}.',
  never:'nikdy',
  just_now:'právě teď',
  ago_min:'před {n} min',
  ago_hour:'před {n} h',
  ago_day:'před {n} dny'
},
en: {
  app_name:'NutriLog',
  nav_today:'Today', nav_log:'Log', nav_suggest:'Suggest', nav_chat:'Chat', nav_review:'Review',
  t_today:'Today', t_log:'Log', t_suggest:'Suggest', t_chat:'Chat', t_review:'Review',
  t_profile:'Profile', t_settings:'Settings',
  back:'Back', close:'Close', save:'Save', cancel:'Cancel', confirm:'Confirm',
  yes:'Yes', no:'No', open_settings:'Settings', loading:'Loading',

  today_intro:'A personal food and nutrient diary.',
  today_noprofile_h:'Start with the profile',
  today_noprofile_p:'Nothing can be calculated without it. It takes about three minutes and can be changed at any time.',
  today_setup_btn:'Fill in the profile',
  energy_eyebrow:'Estimated daily energy',
  range_to:'to',
  kcal:'kcal',
  per_day:'per day',
  why_range_btn:'Why this is a range, not a number',
  floor_binding:'The lower end is held by the floor, not by the calculation.',
  floor_short:'Floor',
  macro_p:'Protein', macro_f:'Fat', macro_c:'Carbohydrate',
  grams:'g',
  protein_per_kg:'{a} to {b} g per kg of body weight',
  protein_low_note:'The lower end of the protein range is low. When losing weight, at least 1.2 g per kg is the usual advice.',
  protein_high_note:'The upper end of the protein range is high. Above roughly 2.2 g per kg there is no demonstrated further benefit.',
  profile_card_h:'Your profile',
  profile_edit:'Edit',
  profile_summary:'{sex}, {age} years, {height} cm, {weight} kg',
  dir_short_lose:'lose slowly', dir_short_maintain:'maintain', dir_short_gain:'gain slowly',
  today_phase_note:'Phase 1 covers the profile, the targets, backup and settings. Food logging arrives in phase 2.',
  targets_h:'Daily targets',
  recompute_note:'Targets are recalculated whenever the profile changes.',

  wr_title:'Why this is a range, not a number',
  wr_intro:'The range is not caution. It is the honest width of what your numbers can support.',
  wr_r1:'The equation (Mifflin, St Jeor) was fitted on groups of people, not on you. For one individual it is typically off by around a tenth either way, sometimes more.',
  wr_r2:'The activity estimate is the largest source of error. Two people who describe their week in exactly the same words can differ by several hundred kcal a day.',
  wr_r3:'The equation knows nothing about your body composition. More muscle raises resting energy use; more fat lowers it per kilogram.',
  wr_r4:'Label numbers are estimates too. EU labelling rules tolerate a difference of up to around a fifth on energy between the label and what is in the packet.',
  wr_r5:'Illness, sleep, cold, medication and the menstrual cycle move daily energy use around from day to day.',
  wr_math_h:'How the range is worked out',
  wr_math_p:'Resting energy from the equation: about {rmr} kcal. Multiplied by the activity band: about {tdee} kcal. Two independent uncertainties (the equation and the activity band) are combined as the square root of the sum of squares rather than simply added; that gives {pct} % either side. The adjustment for your chosen direction is applied last.',
  wr_fix_h:'What would narrow it',
  wr_fix_p:'The only reliable route is your own weight over time. Eat near the same figure for two to three weeks; if your weight holds, that figure is your real expenditure and the equation can be set aside. Weight tracking over time arrives in a later phase.',
  wr_floor_h:'What the floor is',
  wr_floor_p:'The app will never propose a target below {floor} kcal. That is the higher of two numbers: your estimated resting energy use ({rmr} kcal) and a fixed minimum of {abs} kcal. Below resting energy use the body economises elsewhere over time: energy, sleep, mood and muscle.',
  wr_notmed:'This is not medical advice. If you have a condition or take medication that affects weight, appetite or digestion, discuss your targets with a doctor.',

  phase2:'Phase 2', phase3:'Phase 3', phase4:'Phase 4',
  soon_log_h:'Food logging',
  soon_log_p:'Food database lookups, barcode and label reading, manual entry. Every number will carry its source.',
  soon_suggest_h:'Meal suggestions',
  soon_suggest_p:'Suggestions built from your profile, equipment, time and budget. Allergies and refusals will be a hard filter.',
  soon_chat_h:'Ingredient questions',
  soon_chat_p:'Questions about ingredients and recipes, answered against your profile.',
  soon_review_h:'Weekly and monthly review',
  soon_review_p:'Summaries by week and month. Estimated figures will be marked as estimates inside them.',
  soon_nofake:'This screen is deliberately empty. There is no invented data here, so it cannot look finished before it is.',

  p_title:'Profile',
  p_intro:'The targets are calculated from this. Allergies and refusals will apply everywhere in the app.',
  p_basics:'Basics',
  p_sex:'Sex', p_male:'Male', p_female:'Female',
  p_sex_note:'The resting energy equation exists in two forms only, male and female. Pick the one closer to your physiology; it moves the result by about 150 kcal.',
  p_age:'Age', p_years:'years',
  p_height:'Height', p_cm:'cm',
  p_weight:'Current weight', p_kg:'kg',
  p_direction:'Direction',
  dir_lose:'Lose slowly', dir_lose_d:'A modest deficit, about a tenth of daily expenditure.',
  dir_maintain:'Maintain', dir_maintain_d:'The target equals the estimated expenditure.',
  dir_gain:'Gain slowly', dir_gain_d:'A modest surplus, about a fourteenth of daily expenditure.',
  p_activity:'Activity',
  p_activity_note:'Pick what actually describes an ordinary week, not the best one.',
  act1_t:'Mostly seated week', act1_d:'Sitting for most of the day. Walking around the flat and to the shop, no planned exercise.',
  act2_t:'Some movement', act2_d:'30 to 60 minutes of walking a day in total, or one to two lighter training sessions a week.',
  act3_t:'Regular movement', act3_d:'Three to four training sessions a week, or a job that keeps me on my feet half the day.',
  act4_t:'A lot of movement', act4_d:'Hard training five or more times a week, or physically demanding work all day.',
  p_macro:'Macro split',
  ms_balanced:'Balanced', ms_balanced_d:'25 % protein, 30 % fat, 45 % carbohydrate.',
  ms_protein:'Higher protein', ms_protein_d:'35 % protein, 30 % fat, 35 % carbohydrate.',
  ms_lowcarb:'Lower carb', ms_lowcarb_d:'30 % protein, 45 % fat, 25 % carbohydrate.',
  ms_custom:'Manual', ms_custom_d:'Set the percentages yourself.',
  ms_sum:'Sum: {n} %',
  ms_sum_err:'The sum has to be 100 %.',
  p_allergy_h:'Allergies and things I will not eat',
  p_allergy_intro:'An allergy is a hard ban: that ingredient will never appear in a suggestion, a recipe or a chat answer. A refusal is your choice, and the app will treat it just as hard.',
  p_allergy_common:'Common allergens from Annex II of EU Regulation 1169/2011. Tap to add:',
  p_item_ph:'Type an ingredient',
  p_add:'Add',
  p_type_allergy:'Allergy', p_type_refuse:'Will not eat',
  p_synonyms:'Also counts as',
  p_synonyms_ph:'other names, separated by commas',
  p_syn_note:'These names are used when ingredients are checked. The more there are, the more reliable the filter.',
  p_allergy_none:'Nothing yet. That is fine, it can be added at any time.',
  p_remove:'Remove',
  p_cuisines:'Cuisines I like',
  p_cuisine_free_ph:'Another cuisine',
  p_time:'Time available for cooking',
  p_time_weekday:'On a weekday', p_time_weekend:'At the weekend',
  tm1:'up to 15 minutes', tm2:'15 to 30 minutes', tm3:'30 to 60 minutes', tm4:'over an hour',
  p_equipment:'Kitchen equipment',
  eq_hob:'Hob', eq_oven:'Oven', eq_micro:'Microwave', eq_blender:'Blender',
  eq_airfryer:'Air fryer', eq_pressure:'Pressure cooker', eq_none:'None of these',
  p_budget:'Food budget',
  p_budget_note:'Per week, in CZK.',
  bud1:'up to 1 000 CZK', bud2:'1 000 to 1 500 CZK', bud3:'1 500 to 2 500 CZK',
  bud4:'2 500 to 4 000 CZK', bud5:'over 4 000 CZK', bud6:'Not tracking it',
  p_save:'Save profile',
  p_saved:'Profile saved.',
  p_missing:'Missing: {list}',
  p_required:'required',

  set_look:'Appearance and language',
  set_theme:'Theme', th_device:'Follow the phone', th_light:'Light', th_dark:'Dark',
  set_lang:'Language',
  set_profile_h:'Profile and targets',
  set_profile_open:'Open the profile',
  set_keys_h:'API keys',
  set_keys_note:'Keys are stored on this phone only. They never go into the backup or the export. If the phone is lost, revoke them where they were issued.',
  k_anthropic:'Anthropic API key',
  k_usda:'USDA FoodData Central key',
  k_github:'GitHub backup token',
  k_repo:'Backup repository',
  k_repo_ph:'username/repository-name',
  k_branch:'Branch',
  k_show:'Show', k_hide:'Hide',
  test_btn:'Test connection',
  test_running:'Testing...',
  test_need_key:'Fill in the key first.',
  test_need_repo:'Fill in both the key and the repository as username/name.',
  set_models_h:'Models',
  m_chat:'Chat and suggestions', m_vision:'Reading photos and labels', m_analysis:'Weekly and monthly analysis',
  m_note:'Model names change over time. The Test connection button on the Anthropic key also checks whether these three names still exist.',
  m_check_ok:'All three models exist.',
  m_check_bad:'The API does not know these model names: {list}',
  set_price_h:'Prices and spending',
  price_in:'Input, USD per million tokens',
  price_out:'Output, USD per million tokens',
  price_note:'Prefilled from the Anthropic price list as of 9 August 2026. Prices change; check them and overwrite if needed.',
  price_intro_warn:'Sonnet 5 has introductory pricing of 2 and 10 USD until 31 August 2026. After that it is due to rise to 3 and 15 USD.',
  usage_h:'Usage',
  usage_calls:'API calls',
  usage_tokens_in:'Input tokens', usage_tokens_out:'Output tokens',
  usage_cost:'Estimated spend',
  usage_zero:'In phase 1 the app sends no data to a model. Testing the connection uses the model list, which is free. That is why this reads zero.',
  usage_reset:'Reset the counter',

  set_data_h:'Data and backup',
  d_size:'Space used',
  d_persist:'Persistent storage',
  d_persist_yes:'Yes, the browser will not clear the data on its own',
  d_persist_no:'No, the browser may clear the data when space runs short',
  d_unknown:'Unknown',

  dg_h:'What this browser can do',
  dg_p:'Read this when something does not work. It is not about your data, only about what the browser on the phone allows.',
  dg_mode:'How the app is running',
  dg_mode_app:'As an app, with no address bar',
  dg_mode_tab:'As a page in the browser',
  dg_sw:'Working without the internet',
  dg_sw_on:'On, the page is loading from the phone',
  dg_sw_reg:'Ready, it takes effect next time you open the app',
  dg_sw_fail:'Could not be switched on',
  dg_sw_no:'This browser cannot do it',
  dg_barcode:'Reading barcodes (phase 2)',
  dg_camera:'Access to the camera (phase 2)',
  dg_share:'Sharing a file out of the app',
  dg_yes:'Yes',
  dg_no:'No',
  dg_engine:'Browser',
  dg_copy:'Copy this list',
  dg_copied:'Copied. Paste it into the chat.',
  dg_copyfail:'Copying did not work. Select the text above and copy it by hand.',
  dg_note_tab:'The app is running as a page in the browser. It all works, but clearing browser data will erase it. That makes the backup to the repository more important, not less.',

  b_target:'Backup target',
  b_target_none:'Not set up',
  b_last:'Last verified backup',
  b_never:'Never yet',
  b_next:'State',
  b_state_idle:'Idle', b_state_pending:'Waiting to send', b_state_running:'Sending',
  b_state_error:'Error', b_state_offline:'Offline, will retry',
  b_state_empty:'Nothing to back up yet',
  b_last_error:'Last error',
  b_run_now:'Back up now',
  b_export:'Manual export',
  b_export_note:'Saves a dated file to the phone, or sends it through the share sheet.',
  b_export_note_dl:'This browser has no share sheet, so the file lands in the phone downloads instead.',
  b_import:'Restore from a file',
  b_restore_cloud:'Restore from the repository copy',
  b_restore_warn:'Restoring replaces everything on the phone with the contents of the backup. Anything on the phone that is not in the backup will be gone.',
  b_snapshots_h:'Daily copies on the phone',
  b_snapshots_note:'The last seven days. Protects against a bug in the app, not against clearing browser data.',
  b_snapshot_none:'None yet.',
  b_snapshot_restore:'Restore',
  b_secrets_note:'Neither the backup nor the export ever contains API keys. On a new phone you enter them again.',

  danger_h:'Irreversible',
  danger_p:'Erases the profile, the targets, the daily copies and the API keys on this phone. The copy in the repository stays.',
  danger_type:'Type {word} to confirm',
  danger_word:'ERASE',
  danger_btn:'Erase all data',
  danger_done:'Data erased.',

  about_h:'About',
  about_version:'Version',
  about_schema:'Data format',
  about_update:'Check for an update',
  about_update_none:'You have the newest version.',
  about_update_yes:'New version downloaded, the app will reload.',
  about_install:'Install on the phone',
  about_clear_h:'What deletes the data',
  about_clear_p:'If you clear browser data for this site, everything not in a backup is gone: profile, targets and keys. That is why the automatic backup exists.',
  about_token_h:'What the token can reach',
  about_token_p:'The backup token reaches one private repository, the one you named, and only the contents of its files. It cannot reach your other repositories, your account or your billing. If the phone is lost, revoke it in GitHub settings.',
  about_revoke:'Revoke the token on GitHub',

  bar_unconf_new:'Automatic backup is not set up yet. Set it up before you start entering data.',
  bar_unconf_data:'You have data and no backup. Clearing browser data would take it.',
  bar_stale:'Backup has not succeeded for {h} hours.',
  bar_setup:'Set up the backup',
  bar_export:'Export manually',

  err_prefix:'Error',
  err_offline:'The phone is offline.',
  ok:'Done',
  copy:'Copy',
  copied:'Copied.',
  n_a:'None',
  cancelled:'Cancelled.',
  restore_ok:'Data restored.',
  import_bad_file:'This file does not look like a NutriLog backup. Nothing was changed.',
  import_bad_schema:'This file comes from a newer version of the app (format {n}). This version cannot read it, so it did not try. Nothing was changed.',
  backup_ok:'Backup sent.',
  backup_same:'No change, the backup is current.',
  backup_empty:'Nothing to back up yet.',
  backup_fail:'The backup failed.',
  repo_public_warn:'Careful: this repository is public. Your food diary would be on the internet. Use a private one.',
  repo_is_pages_warn:'Careful: this looks like the same repository this app is served from. The backup would be published. Use a different, private one.',
  repo_private_ok:'The repository is private.',
  write_ok:'Writing to the repository works.',
  write_fail:'Writing to the repository does not work.',
  delete_fail:'The test file could not be deleted, but writing works. You can delete nutrilog-write-test.txt by hand.',
  usda_ok:'USDA answered. The browser can reach the database directly, so phase 2 can build on this.',
  anthropic_ok:'The key works. Models available: {n}.',
  never:'never',
  just_now:'just now',
  ago_min:'{n} min ago',
  ago_hour:'{n} h ago',
  ago_day:'{n} days ago'
}
};
