const STR = {
cs: {
  app_name:'NutriLog',
  nav_today:'Dnes', nav_log:'Deník', nav_recipes:'Recepty', nav_chat:'Chat', nav_review:'Přehled',
  t_today:'Dnes', t_log:'Deník', t_recipes:'Recepty', t_recipe:'Recept', t_chat:'Chat', t_review:'Přehled',
  t_profile:'Profil', t_settings:'Nastavení',
  back:'Zpět', close:'Zavřít', save:'Uložit', cancel:'Zrušit', confirm:'Potvrdit',
  yes:'Ano', no:'Ne', open_settings:'Nastavení', loading:'Načítám',

  /* Today */
  today_intro:'Osobní deník jídla a živin.',
  today_noprofile_h:'Začněte profilem',
  today_noprofile_p:'Bez profilu nelze spočítat nic. Vyplnění zabere asi tři minuty a kdykoli se dá změnit.',
  today_setup_btn:'Vyplnit profil',
  energy_eyebrow:'Odhad denní energie',
  range_to:'až',
  kcal:'kcal',
  per_day:'na den',
  why_range_btn:'Proč je to rozsah a ne číslo',
  floor_binding:'Spodní hranici drží podlaha, ne výpočet.',
  floor_short:'Podlaha',
  macro_p:'Bílkoviny', macro_f:'Tuky', macro_c:'Sacharidy',
  grams:'g',
  protein_per_kg:'{a} až {b} g na kg váhy',
  protein_low_note:'Spodní konec rozsahu bílkovin je nízký. Při hubnutí se obvykle doporučuje aspoň 1,2 g na kg váhy.',
  protein_high_note:'Horní konec rozsahu bílkovin je vysoký. Nad zhruba 2,2 g na kg váhy už další přínos není prokázaný.',
  profile_card_h:'Váš profil',
  profile_edit:'Upravit',
  profile_summary:'{sex}, {age} let, {height} cm, {weight} kg',
  dir_short_lose:'pomalu hubnout', dir_short_maintain:'držet váhu', dir_short_gain:'pomalu přibírat',
  today_phase_note:'Ve fázi 1 umí aplikace profil, cíle, zálohu a nastavení. Zapisování jídla přijde ve fázi 2.',
  targets_h:'Denní cíle',
  recompute_note:'Cíle se přepočítají po každé změně profilu.',

  /* Why a range */
  wr_title:'Proč je to rozsah a ne číslo',
  wr_intro:'Ten rozsah není opatrnost. Je to poctivá šíře toho, co se z vašich údajů dá spočítat.',
  wr_r1:'Rovnice byly sestaveny na skupinách lidí, ne na vás. U jednotlivce se typicky mýlí zhruba o desetinu nahoru nebo dolů, občas víc. Bez nastavení pohlaví aplikace bere střed mezi mužskou a ženskou variantou, což přidá asi 80 kcal nejistoty; bez výšky počítá jen z váhy a rozpětí je širší.',
  wr_r2:'Odhad aktivity je největší zdroj chyby. Dva lidé, kteří svůj týden popíší úplně stejně, se můžou lišit o několik set kcal denně.',
  wr_r3:'Rovnice nezná složení vašeho těla. Více svalů zvyšuje klidový výdej, více tuku ho na kilogram snižuje.',
  wr_r4:'Čísla na obalech jsou také jen odhad. Evropská pravidla pro označování připouštějí u energie rozdíl až kolem pětiny oproti tomu, co je v balení.',
  wr_r5:'Nemoc, spánek, chlad, léky a menstruační cyklus mění denní výdej ze dne na den.',
  wr_math_h:'Jak je rozsah spočítaný',
  wr_math_p:'Klidový výdej podle rovnice: asi {rmr} kcal. Vynásobeno pásmem aktivity: asi {tdee} kcal. Dvě nezávislé nejistoty (rovnice a aktivita) se skládají odmocninou ze součtu čtverců, ne prostým sčítáním; vychází z toho {pct} % na každou stranu. Nakonec se přičte nebo odečte úprava podle zvoleného směru.',
  wr_fix_h:'Co rozsah zúží',
  wr_fix_p:'Jediná spolehlivá cesta je vaše vlastní váha v čase. Když se dva až tři týdny jí kolem stejné hodnoty a váha se drží, je ta hodnota vaším skutečným výdejem a rovnice se dá odložit. Sledování váhy v čase přijde v další fázi.',
  wr_floor_h:'Co je podlaha',
  wr_floor_p:'Aplikace nikdy nenavrhne cíl pod {floor} kcal. Ta hodnota je vyšší z dvou: váš odhadovaný klidový výdej ({rmr} kcal) a pevné minimum {abs} kcal. Pod klidovým výdejem tělo dlouhodobě šetří jinde: energií, spánkem, náladou a svalovou hmotou.',
  wr_notmed:'Toto není lékařská rada. Pokud máte onemocnění nebo berete léky, které ovlivňují váhu, chuť k jídlu nebo trávení, proberte cíle s lékařem.',

  /* Later phases */
  phase2:'Fáze 2', phase3:'Fáze 3', phase4:'Fáze 4',
  soon_log_h:'Zapisování jídla',
  soon_log_p:'Vyhledání v databázi potravin, čtení čárových kódů a etiket, ruční zadání. Každé číslo si ponese svůj zdroj.',
  soon_suggest_h:'Návrhy jídel',
  soon_suggest_p:'Návrhy podle vašeho profilu, vybavení, času a rozpočtu. Alergie a věci, které nejíte, budou tvrdý filtr.',
  soon_chat_h:'Otázky na suroviny',
  soon_chat_p:'Dotazy na suroviny a recepty, zodpovězené s ohledem na váš profil.',
  soon_review_h:'Týdenní a měsíční přehled',
  soon_review_p:'Souhrny za týden a měsíc. Odhadované hodnoty v nich budou označené jako odhady.',
  soon_nofake:'Tato obrazovka je záměrně prázdná. Nejsou tu vymyšlená data, aby nevypadala hotově dřív, než bude.',

  /* Profile */
  p_title:'Profil',
  p_intro:'Z těchto údajů se počítají cíle. Alergie a věci, které nejíte, budou platit všude v aplikaci.',
  p_basics:'Základní údaje',
  p_sex:'Pohlaví', p_male:'Muž', p_female:'Žena',
  p_sex_note:'Rovnice pro klidový výdej existuje jen ve dvou variantách, mužské a ženské. Vyberte tu, která se lépe blíží vaší fyziologii; ovlivní to výsledek zhruba o 150 kcal.',
  p_age:'Věk', p_years:'let',
  p_height:'Výška', p_cm:'cm',
  p_weight:'Současná váha', p_kg:'kg',
  p_direction:'Směr',
  dir_lose:'Pomalu hubnout', dir_lose_d:'Mírný deficit, zhruba desetina denního výdeje.',
  dir_maintain:'Držet váhu', dir_maintain_d:'Cíl se rovná odhadovanému výdeji.',
  dir_gain:'Pomalu přibírat', dir_gain_d:'Mírný přebytek, zhruba čtrnáctina denního výdeje.',
  p_activity:'Aktivita',
  p_activity_note:'Vyberte to, co skutečně popisuje běžný týden, ne ten nejlepší.',
  act1_t:'Převážně sedavý týden', act1_d:'Většinu dne sedím. Chůze po bytě a do obchodu, žádné plánované cvičení.',
  act2_t:'Trochu pohybu', act2_d:'Denně 30 až 60 minut chůze dohromady, nebo jeden až dva lehčí tréninky týdně.',
  act3_t:'Pravidelný pohyb', act3_d:'Tři až čtyři tréninky týdně, nebo práce, při které jsem půl dne na nohou.',
  act4_t:'Hodně pohybu', act4_d:'Tvrdý trénink pětkrát týdně a víc, nebo fyzicky náročná práce celý den.',
  p_macro:'Rozdělení živin',
  ms_balanced:'Vyvážené', ms_balanced_d:'25 % bílkoviny, 30 % tuky, 45 % sacharidy.',
  ms_protein:'Více bílkovin', ms_protein_d:'35 % bílkoviny, 30 % tuky, 35 % sacharidy.',
  ms_lowcarb:'Méně sacharidů', ms_lowcarb_d:'30 % bílkoviny, 45 % tuky, 25 % sacharidy.',
  ms_custom:'Vlastní', ms_custom_d:'Zadejte si procenta sami.',
  ms_sum:'Součet: {n} %',
  ms_sum_err:'Součet musí být 100 %.',
  p_allergy_h:'Alergie a co nejím',
  p_allergy_intro:'Alergie je tvrdý zákaz: taková surovina se nikdy neobjeví v návrhu, receptu ani v odpovědi chatu. „Nejím“ je vaše volba, aplikace ji bude respektovat stejně tvrdě.',
  p_allergy_common:'Časté alergeny podle přílohy II nařízení EU 1169/2011. Klepnutím přidáte:',
  p_item_ph:'Napište surovinu',
  p_add:'Přidat',
  p_type_allergy:'Alergie', p_type_refuse:'Nejím',
  p_synonyms:'Také se počítá jako',
  p_synonyms_ph:'další názvy, oddělené čárkou',
  p_syn_note:'Tyto názvy se použijí při kontrole surovin. Čím víc jich je, tím spolehlivější filtr.',
  p_allergy_none:'Zatím nic. To je v pořádku, dá se doplnit kdykoli.',
  p_remove:'Odebrat',
  p_cuisines:'Kuchyně, které mám rád',
  p_cuisine_free_ph:'Jiná kuchyně',
  p_time:'Kolik času mám na vaření',
  p_time_weekday:'Ve všední den', p_time_weekend:'O víkendu',
  tm1:'do 15 minut', tm2:'15 až 30 minut', tm3:'30 až 60 minut', tm4:'přes hodinu',
  p_equipment:'Vybavení kuchyně',
  eq_hob:'Varná deska', eq_oven:'Trouba', eq_micro:'Mikrovlnka', eq_blender:'Mixér',
  eq_airfryer:'Horkovzdušná fritéza', eq_pressure:'Tlakový hrnec', eq_none:'Nic z toho',
  p_budget:'Rozpočet na jídlo',
  p_budget_note:'Na týden, v korunách.',
  bud1:'do 1 000 Kč', bud2:'1 000 až 1 500 Kč', bud3:'1 500 až 2 500 Kč',
  bud4:'2 500 až 4 000 Kč', bud5:'přes 4 000 Kč', bud6:'Nesleduji',
  p_save:'Uložit profil',
  p_saved:'Profil uložen.',
  p_missing:'Chybí: {list}',
  p_required:'povinné',

  /* Settings */
  set_look:'Vzhled a jazyk',
  set_theme:'Motiv', th_device:'Podle telefonu', th_light:'Světlý', th_dark:'Tmavý',
  set_lang:'Jazyk',
  set_profile_h:'Profil a cíle',
  set_profile_open:'Otevřít profil',
  set_keys_h:'Klíče k API',
  set_keys_note:'Klíče se ukládají jen do tohoto telefonu. Nikdy neodcházejí do zálohy ani do exportu. Když telefon ztratíte, klíče zrušte u jejich vydavatele.',
  k_anthropic:'Anthropic API klíč',
  k_usda:'USDA FoodData Central klíč',
  k_github:'GitHub token pro zálohu',
  k_repo:'Repozitář pro zálohu',
  k_repo_ph:'uzivatel/nazev-repozitare',
  k_branch:'Větev',
  k_show:'Ukázat', k_hide:'Skrýt',
  test_btn:'Ověřit připojení',
  test_running:'Ověřuji...',
  test_need_key:'Nejdřív vyplňte klíč.',
  test_need_repo:'Nejdřív vyplňte klíč i repozitář ve tvaru uzivatel/nazev.',
  set_models_h:'Modely',
  m_chat:'Chat a návrhy', m_vision:'Čtení fotek a etiket', m_analysis:'Týdenní a měsíční rozbor',
  m_note:'Názvy modelů se časem mění. Tlačítko Ověřit připojení u klíče Anthropic zároveň zkontroluje, jestli tyto tři názvy pořád existují.',
  m_check_ok:'Všechny tři modely existují.',
  m_check_bad:'Tyto názvy modelů API nezná: {list}',
  set_price_h:'Ceny a útrata',
  price_in:'Vstup, USD za milion tokenů',
  price_out:'Výstup, USD za milion tokenů',
  price_note:'Předvyplněno z ceníku Anthropic k 21. září 2026. Ceny se mění; ověřte si je a případně přepište.',
  price_intro_warn:'Sonnet 5 má do 31. srpna 2026 zaváděcí cenu 2 a 10 USD. Poté se má zvednout na 3 a 15 USD.',
  usage_h:'Spotřeba',
  usage_calls:'Volání API',
  usage_tokens_in:'Vstupní tokeny', usage_tokens_out:'Výstupní tokeny',
  usage_cost:'Odhad útraty',
  usage_zero:'Ve fázi 1 aplikace neposílá do modelu žádná data. Ověření připojení používá seznam modelů, což je zdarma. Proto je tu zatím nula.',
  usage_reset:'Vynulovat počítadlo',

  set_data_h:'Data a záloha',
  d_size:'Zabrané místo',
  d_persist:'Trvalé úložiště',
  d_persist_yes:'Ano, prohlížeč data sám nesmaže',
  d_persist_no:'Ne, prohlížeč může data při nedostatku místa smazat',
  d_unknown:'Neznámé',

  dg_h:'Co tenhle prohlížeč umí',
  dg_p:'Přečti si tohle, když něco nejde. Netýká se to tvých dat, jen toho, co prohlížeč v telefonu dovolí.',
  dg_mode:'Jak je aplikace spuštěná',
  dg_mode_app:'Jako aplikace, bez adresního řádku',
  dg_mode_tab:'Jako stránka v prohlížeči',
  dg_sw:'Práce bez internetu',
  dg_sw_on:'Zapnutá, stránka se načítá z telefonu',
  dg_sw_reg:'Připravená, projeví se po dalším otevření',
  dg_sw_fail:'Nepodařilo se zapnout',
  dg_sw_no:'Tenhle prohlížeč to neumí',
  dg_barcode:'Čtení čárových kódů',
  dg_camera:'Přístup ke kameře',
  dg_share:'Sdílení souboru z aplikace',
  dg_yes:'Ano',
  dg_no:'Ne',
  dg_engine:'Prohlížeč',
  dg_copy:'Zkopírovat tenhle výpis',
  dg_copied:'Zkopírováno. Vlož mi to do chatu.',
  dg_copyfail:'Kopírování nevyšlo. Označ text nahoře a zkopíruj ho ručně.',
  dg_note_tab:'Aplikace běží jako stránka v prohlížeči. Funguje celá, ale smazání dat prohlížeče ji vymaže. O to důležitější je záloha do repozitáře.',

  b_target:'Cíl zálohy',
  b_target_none:'Nenastaveno',
  b_last:'Poslední ověřená záloha',
  b_never:'Zatím nikdy',
  b_next:'Stav',
  b_state_idle:'Nečinné', b_state_pending:'Čeká na odeslání', b_state_running:'Odesílám',
  b_state_error:'Chyba', b_state_offline:'Bez připojení, zkusím to znovu',
  b_state_empty:'Zatím není co zálohovat',
  b_last_error:'Poslední chyba',
  b_run_now:'Zálohovat hned',
  b_export:'Ruční export',
  b_export_note:'Uloží soubor s datem do telefonu nebo ho pošle přes sdílení.',
  b_export_note_dl:'Tenhle prohlížeč neumí sdílení, takže se soubor uloží mezi stažené soubory v telefonu.',
  b_import:'Obnovit ze souboru',
  b_restore_cloud:'Obnovit z kopie v repozitáři',
  b_restore_warn:'Obnovení nahradí všechna data v telefonu obsahem zálohy. Co je v telefonu teď a není v záloze, zmizí.',
  b_snapshots_h:'Denní kopie v telefonu',
  b_snapshots_note:'Posledních sedm dní. Chrání před chybou v aplikaci, nechrání před smazáním dat prohlížeče.',
  b_snapshot_none:'Zatím žádné.',
  b_snapshot_restore:'Obnovit',
  b_secrets_note:'Záloha ani export nikdy neobsahují klíče k API. Na novém telefonu je zadáte znovu.',

  danger_h:'Nevratné',
  danger_p:'Smaže profil, deník, doplňky, vlastní recepty, denní kopie i klíče k API v tomto telefonu. Kopie v repozitáři zůstane.',
  danger_type:'Pro potvrzení napište {word}',
  danger_word:'SMAZAT',
  danger_btn:'Smazat všechna data',
  danger_done:'Data smazána.',

  about_h:'O aplikaci',
  about_version:'Verze',
  about_schema:'Formát dat',
  about_update:'Zkontrolovat aktualizaci',
  about_update_none:'Máte nejnovější verzi.',
  about_update_yes:'Nová verze stažena, aplikace se načte znovu.',
  about_install:'Nainstalovat do telefonu',
  about_clear_h:'Co smaže data',
  about_clear_p:'Když v prohlížeči smažete data pro tuto stránku, zmizí všechno, co není v záloze: profil, deník, doplňky i klíče. Proto existuje automatická záloha.',
  about_token_h:'Co dosáhne token',
  about_token_p:'Token pro zálohu má přístup jen k jednomu soukromému repozitáři, který jste zadali, a jen k obsahu souborů. Nemá přístup k ostatním repozitářům, k účtu ani k platbám. Když telefon ztratíte, zrušte ho v nastavení GitHubu.',
  about_revoke:'Zrušit token na GitHubu',

  /* backup bar */
  bar_unconf_new:'Automatická záloha zatím není nastavená. Nastavte ji dřív, než začnete zapisovat data.',
  bar_unconf_data:'Máte data a nemáte zálohu. Když smažete data prohlížeče, zmizí.',
  bar_stale:'Záloha se nepovedla už {h} hodin.',
  bar_setup:'Nastavit zálohu',
  bar_export:'Exportovat ručně',

  /* generic */
  err_prefix:'Chyba',
  err_offline:'Telefon je bez připojení.',
  ok:'Hotovo',
  copy:'Kopírovat',
  copied:'Zkopírováno.',
  n_a:'Není',
  cancelled:'Zrušeno.',
  restore_ok:'Data obnovena.',
  import_bad_file:'Tento soubor nevypadá jako záloha NutriLogu. Nic se nezměnilo.',
  import_bad_schema:'Tento soubor je z novější verze aplikace (formát {n}). Tahle verze ho neumí přečíst, tak ho radši nepoužila. Nic se nezměnilo.',
  backup_ok:'Záloha odeslána.',
  backup_same:'Beze změny, záloha je aktuální.',
  backup_empty:'Zatím není co zálohovat.',
  backup_fail:'Záloha se nepovedla.',
  repo_public_warn:'Pozor: tento repozitář je veřejný. Váš deník jídla by byl na internetu. Použijte soukromý.',
  repo_is_pages_warn:'Pozor: tohle je zřejmě stejný repozitář, ze kterého běží tahle aplikace. Záloha by se zveřejnila. Použijte jiný, soukromý.',
  repo_private_ok:'Repozitář je soukromý.',
  write_ok:'Zápis do repozitáře funguje.',
  write_fail:'Zápis do repozitáře nefunguje.',
  delete_fail:'Zkušební soubor se nepodařilo smazat, ale zápis funguje. Soubor nutrilog-write-test.txt můžete smazat ručně.',
  usda_ok:'USDA odpovědělo. Prohlížeč se k databázi dostane přímo, takže fáze 2 může stavět na tomhle.',
  anthropic_ok:'Klíč funguje. Modelů dostupných: {n}.',
  never:'nikdy',
  just_now:'právě teď',
  ago_min:'před {n} min',
  ago_hour:'před {n} h',
  ago_day:'před {n} dny'
},
en: {
  app_name:'NutriLog',
  nav_today:'Today', nav_log:'Log', nav_recipes:'Recipes', nav_chat:'Chat', nav_review:'Review',
  t_today:'Today', t_log:'Log', t_recipes:'Recipes', t_recipe:'Recipe', t_chat:'Chat', t_review:'Review',
  t_profile:'Profile', t_settings:'Settings',
  back:'Back', close:'Close', save:'Save', cancel:'Cancel', confirm:'Confirm',
  yes:'Yes', no:'No', open_settings:'Settings', loading:'Loading',

  today_intro:'A personal food and nutrient diary.',
  today_noprofile_h:'Start with the profile',
  today_noprofile_p:'Nothing can be calculated without it. It takes about three minutes and can be changed at any time.',
  today_setup_btn:'Fill in the profile',
  energy_eyebrow:'Estimated daily energy',
  range_to:'to',
  kcal:'kcal',
  per_day:'per day',
  why_range_btn:'Why this is a range, not a number',
  floor_binding:'The lower end is held by the floor, not by the calculation.',
  floor_short:'Floor',
  macro_p:'Protein', macro_f:'Fat', macro_c:'Carbohydrate',
  grams:'g',
  protein_per_kg:'{a} to {b} g per kg of body weight',
  protein_low_note:'The lower end of the protein range is low. When losing weight, at least 1.2 g per kg is the usual advice.',
  protein_high_note:'The upper end of the protein range is high. Above roughly 2.2 g per kg there is no demonstrated further benefit.',
  profile_card_h:'Your profile',
  profile_edit:'Edit',
  profile_summary:'{sex}, {age} years, {height} cm, {weight} kg',
  dir_short_lose:'lose slowly', dir_short_maintain:'maintain', dir_short_gain:'gain slowly',
  today_phase_note:'Phase 1 covers the profile, the targets, backup and settings. Food logging arrives in phase 2.',
  targets_h:'Daily targets',
  recompute_note:'Targets are recalculated whenever the profile changes.',

  wr_title:'Why this is a range, not a number',
  wr_intro:'The range is not caution. It is the honest width of what your numbers can support.',
  wr_r1:'The equations were fitted on groups of people, not on you. For one individual they are typically off by around a tenth either way, sometimes more. Without a sex setting the app takes the midpoint of the male and female versions, which adds about 80 kcal of uncertainty; without height it works from weight only and the range is wider.',
  wr_r2:'The activity estimate is the largest source of error. Two people who describe their week in exactly the same words can differ by several hundred kcal a day.',
  wr_r3:'The equation knows nothing about your body composition. More muscle raises resting energy use; more fat lowers it per kilogram.',
  wr_r4:'Label numbers are estimates too. EU labelling rules tolerate a difference of up to around a fifth on energy between the label and what is in the packet.',
  wr_r5:'Illness, sleep, cold, medication and the menstrual cycle move daily energy use around from day to day.',
  wr_math_h:'How the range is worked out',
  wr_math_p:'Resting energy from the equation: about {rmr} kcal. Multiplied by the activity band: about {tdee} kcal. Two independent uncertainties (the equation and the activity band) are combined as the square root of the sum of squares rather than simply added; that gives {pct} % either side. The adjustment for your chosen direction is applied last.',
  wr_fix_h:'What would narrow it',
  wr_fix_p:'The only reliable route is your own weight over time. Eat near the same figure for two to three weeks; if your weight holds, that figure is your real expenditure and the equation can be set aside. Weight tracking over time arrives in a later phase.',
  wr_floor_h:'What the floor is',
  wr_floor_p:'The app will never propose a target below {floor} kcal. That is the higher of two numbers: your estimated resting energy use ({rmr} kcal) and a fixed minimum of {abs} kcal. Below resting energy use the body economises elsewhere over time: energy, sleep, mood and muscle.',
  wr_notmed:'This is not medical advice. If you have a condition or take medication that affects weight, appetite or digestion, discuss your targets with a doctor.',

  phase2:'Phase 2', phase3:'Phase 3', phase4:'Phase 4',
  soon_log_h:'Food logging',
  soon_log_p:'Food database lookups, barcode and label reading, manual entry. Every number will carry its source.',
  soon_suggest_h:'Meal suggestions',
  soon_suggest_p:'Suggestions built from your profile, equipment, time and budget. Allergies and refusals will be a hard filter.',
  soon_chat_h:'Ingredient questions',
  soon_chat_p:'Questions about ingredients and recipes, answered against your profile.',
  soon_review_h:'Weekly and monthly review',
  soon_review_p:'Summaries by week and month. Estimated figures will be marked as estimates inside them.',
  soon_nofake:'This screen is deliberately empty. There is no invented data here, so it cannot look finished before it is.',

  p_title:'Profile',
  p_intro:'The targets are calculated from this. Allergies and refusals will apply everywhere in the app.',
  p_basics:'Basics',
  p_sex:'Sex', p_male:'Male', p_female:'Female',
  p_sex_note:'The resting energy equation exists in two forms only, male and female. Pick the one closer to your physiology; it moves the result by about 150 kcal.',
  p_age:'Age', p_years:'years',
  p_height:'Height', p_cm:'cm',
  p_weight:'Current weight', p_kg:'kg',
  p_direction:'Direction',
  dir_lose:'Lose slowly', dir_lose_d:'A modest deficit, about a tenth of daily expenditure.',
  dir_maintain:'Maintain', dir_maintain_d:'The target equals the estimated expenditure.',
  dir_gain:'Gain slowly', dir_gain_d:'A modest surplus, about a fourteenth of daily expenditure.',
  p_activity:'Activity',
  p_activity_note:'Pick what actually describes an ordinary week, not the best one.',
  act1_t:'Mostly seated week', act1_d:'Sitting for most of the day. Walking around the flat and to the shop, no planned exercise.',
  act2_t:'Some movement', act2_d:'30 to 60 minutes of walking a day in total, or one to two lighter training sessions a week.',
  act3_t:'Regular movement', act3_d:'Three to four training sessions a week, or a job that keeps me on my feet half the day.',
  act4_t:'A lot of movement', act4_d:'Hard training five or more times a week, or physically demanding work all day.',
  p_macro:'Macro split',
  ms_balanced:'Balanced', ms_balanced_d:'25 % protein, 30 % fat, 45 % carbohydrate.',
  ms_protein:'Higher protein', ms_protein_d:'35 % protein, 30 % fat, 35 % carbohydrate.',
  ms_lowcarb:'Lower carb', ms_lowcarb_d:'30 % protein, 45 % fat, 25 % carbohydrate.',
  ms_custom:'Manual', ms_custom_d:'Set the percentages yourself.',
  ms_sum:'Sum: {n} %',
  ms_sum_err:'The sum has to be 100 %.',
  p_allergy_h:'Allergies and things I will not eat',
  p_allergy_intro:'An allergy is a hard ban: that ingredient will never appear in a suggestion, a recipe or a chat answer. A refusal is your choice, and the app will treat it just as hard.',
  p_allergy_common:'Common allergens from Annex II of EU Regulation 1169/2011. Tap to add:',
  p_item_ph:'Type an ingredient',
  p_add:'Add',
  p_type_allergy:'Allergy', p_type_refuse:'Will not eat',
  p_synonyms:'Also counts as',
  p_synonyms_ph:'other names, separated by commas',
  p_syn_note:'These names are used when ingredients are checked. The more there are, the more reliable the filter.',
  p_allergy_none:'Nothing yet. That is fine, it can be added at any time.',
  p_remove:'Remove',
  p_cuisines:'Cuisines I like',
  p_cuisine_free_ph:'Another cuisine',
  p_time:'Time available for cooking',
  p_time_weekday:'On a weekday', p_time_weekend:'At the weekend',
  tm1:'up to 15 minutes', tm2:'15 to 30 minutes', tm3:'30 to 60 minutes', tm4:'over an hour',
  p_equipment:'Kitchen equipment',
  eq_hob:'Hob', eq_oven:'Oven', eq_micro:'Microwave', eq_blender:'Blender',
  eq_airfryer:'Air fryer', eq_pressure:'Pressure cooker', eq_none:'None of these',
  p_budget:'Food budget',
  p_budget_note:'Per week, in CZK.',
  bud1:'up to 1 000 CZK', bud2:'1 000 to 1 500 CZK', bud3:'1 500 to 2 500 CZK',
  bud4:'2 500 to 4 000 CZK', bud5:'over 4 000 CZK', bud6:'Not tracking it',
  p_save:'Save profile',
  p_saved:'Profile saved.',
  p_missing:'Missing: {list}',
  p_required:'required',

  set_look:'Appearance and language',
  set_theme:'Theme', th_device:'Follow the phone', th_light:'Light', th_dark:'Dark',
  set_lang:'Language',
  set_profile_h:'Profile and targets',
  set_profile_open:'Open the profile',
  set_keys_h:'API keys',
  set_keys_note:'Keys are stored on this phone only. They never go into the backup or the export. If the phone is lost, revoke them where they were issued.',
  k_anthropic:'Anthropic API key',
  k_usda:'USDA FoodData Central key',
  k_github:'GitHub backup token',
  k_repo:'Backup repository',
  k_repo_ph:'username/repository-name',
  k_branch:'Branch',
  k_show:'Show', k_hide:'Hide',
  test_btn:'Test connection',
  test_running:'Testing...',
  test_need_key:'Fill in the key first.',
  test_need_repo:'Fill in both the key and the repository as username/name.',
  set_models_h:'Models',
  m_chat:'Chat and suggestions', m_vision:'Reading photos and labels', m_analysis:'Weekly and monthly analysis',
  m_note:'Model names change over time. The Test connection button on the Anthropic key also checks whether these three names still exist.',
  m_check_ok:'All three models exist.',
  m_check_bad:'The API does not know these model names: {list}',
  set_price_h:'Prices and spending',
  price_in:'Input, USD per million tokens',
  price_out:'Output, USD per million tokens',
  price_note:'Prefilled from the Anthropic price list as of 21 September 2026. Prices change; check them and overwrite if needed.',
  price_intro_warn:'Sonnet 5 has introductory pricing of 2 and 10 USD until 31 August 2026. After that it is due to rise to 3 and 15 USD.',
  usage_h:'Usage',
  usage_calls:'API calls',
  usage_tokens_in:'Input tokens', usage_tokens_out:'Output tokens',
  usage_cost:'Estimated spend',
  usage_zero:'In phase 1 the app sends no data to a model. Testing the connection uses the model list, which is free. That is why this reads zero.',
  usage_reset:'Reset the counter',

  set_data_h:'Data and backup',
  d_size:'Space used',
  d_persist:'Persistent storage',
  d_persist_yes:'Yes, the browser will not clear the data on its own',
  d_persist_no:'No, the browser may clear the data when space runs short',
  d_unknown:'Unknown',

  dg_h:'What this browser can do',
  dg_p:'Read this when something does not work. It is not about your data, only about what the browser on the phone allows.',
  dg_mode:'How the app is running',
  dg_mode_app:'As an app, with no address bar',
  dg_mode_tab:'As a page in the browser',
  dg_sw:'Working without the internet',
  dg_sw_on:'On, the page is loading from the phone',
  dg_sw_reg:'Ready, it takes effect next time you open the app',
  dg_sw_fail:'Could not be switched on',
  dg_sw_no:'This browser cannot do it',
  dg_barcode:'Reading barcodes',
  dg_camera:'Access to the camera',
  dg_share:'Sharing a file out of the app',
  dg_yes:'Yes',
  dg_no:'No',
  dg_engine:'Browser',
  dg_copy:'Copy this list',
  dg_copied:'Copied. Paste it into the chat.',
  dg_copyfail:'Copying did not work. Select the text above and copy it by hand.',
  dg_note_tab:'The app is running as a page in the browser. It all works, but clearing browser data will erase it. That makes the backup to the repository more important, not less.',

  b_target:'Backup target',
  b_target_none:'Not set up',
  b_last:'Last verified backup',
  b_never:'Never yet',
  b_next:'State',
  b_state_idle:'Idle', b_state_pending:'Waiting to send', b_state_running:'Sending',
  b_state_error:'Error', b_state_offline:'Offline, will retry',
  b_state_empty:'Nothing to back up yet',
  b_last_error:'Last error',
  b_run_now:'Back up now',
  b_export:'Manual export',
  b_export_note:'Saves a dated file to the phone, or sends it through the share sheet.',
  b_export_note_dl:'This browser has no share sheet, so the file lands in the phone downloads instead.',
  b_import:'Restore from a file',
  b_restore_cloud:'Restore from the repository copy',
  b_restore_warn:'Restoring replaces everything on the phone with the contents of the backup. Anything on the phone that is not in the backup will be gone.',
  b_snapshots_h:'Daily copies on the phone',
  b_snapshots_note:'The last seven days. Protects against a bug in the app, not against clearing browser data.',
  b_snapshot_none:'None yet.',
  b_snapshot_restore:'Restore',
  b_secrets_note:'Neither the backup nor the export ever contains API keys. On a new phone you enter them again.',

  danger_h:'Irreversible',
  danger_p:'Erases the profile, the diary, supplements, your own recipes, the daily copies and the API keys on this phone. The copy in the repository stays.',
  danger_type:'Type {word} to confirm',
  danger_word:'ERASE',
  danger_btn:'Erase all data',
  danger_done:'Data erased.',

  about_h:'About',
  about_version:'Version',
  about_schema:'Data format',
  about_update:'Check for an update',
  about_update_none:'You have the newest version.',
  about_update_yes:'New version downloaded, the app will reload.',
  about_install:'Install on the phone',
  about_clear_h:'What deletes the data',
  about_clear_p:'If you clear browser data for this site, everything not in a backup is gone: profile, diary, supplements and keys. That is why the automatic backup exists.',
  about_token_h:'What the token can reach',
  about_token_p:'The backup token reaches one private repository, the one you named, and only the contents of its files. It cannot reach your other repositories, your account or your billing. If the phone is lost, revoke it in GitHub settings.',
  about_revoke:'Revoke the token on GitHub',

  bar_unconf_new:'Automatic backup is not set up yet. Set it up before you start entering data.',
  bar_unconf_data:'You have data and no backup. Clearing browser data would take it.',
  bar_stale:'Backup has not succeeded for {h} hours.',
  bar_setup:'Set up the backup',
  bar_export:'Export manually',

  err_prefix:'Error',
  err_offline:'The phone is offline.',
  ok:'Done',
  copy:'Copy',
  copied:'Copied.',
  n_a:'None',
  cancelled:'Cancelled.',
  restore_ok:'Data restored.',
  import_bad_file:'This file does not look like a NutriLog backup. Nothing was changed.',
  import_bad_schema:'This file comes from a newer version of the app (format {n}). This version cannot read it, so it did not try. Nothing was changed.',
  backup_ok:'Backup sent.',
  backup_same:'No change, the backup is current.',
  backup_empty:'Nothing to back up yet.',
  backup_fail:'The backup failed.',
  repo_public_warn:'Careful: this repository is public. Your food diary would be on the internet. Use a private one.',
  repo_is_pages_warn:'Careful: this looks like the same repository this app is served from. The backup would be published. Use a different, private one.',
  repo_private_ok:'The repository is private.',
  write_ok:'Writing to the repository works.',
  write_fail:'Writing to the repository does not work.',
  delete_fail:'The test file could not be deleted, but writing works. You can delete nutrilog-write-test.txt by hand.',
  usda_ok:'USDA answered. The browser can reach the database directly, so phase 2 can build on this.',
  anthropic_ok:'The key works. Models available: {n}.',
  never:'never',
  just_now:'just now',
  ago_min:'{n} min ago',
  ago_hour:'{n} h ago',
  ago_day:'{n} days ago'
}
};


/* ---------- v0.2 additions ---------- */
Object.assign(STR.cs, {
  mac_p:'B', mac_f:'T', mac_c:'S',
  today:'Dnes', db_blocked:'Aplikace je otevřená ještě v jiné kartě. Zavřete ji, aby se mohla aktualizovat.',
  slot_breakfast:'Snídaně', slot_lunch:'Oběd', slot_snack:'Svačina', slot_dinner:'Večeře', slot_other:'Ostatní',
  nut_fib:'Vláknina',
  td_eaten:'Dnes snědeno', td_range:'Cíl {a} až {b} kcal', td_left:'do cíle chybí {a} až {b} kcal', td_inrange:'jste v rozsahu, rezerva {b} kcal', td_over:'nad horní hranicí o {n} kcal',
  td_meals:'Jídla', td_add:'přidat', td_next:'Nápady na {slot}', td_more:'Další nápady',
  fab_supp:'Doplňky stravy',
  add_title:'Přidat: {slot}',
  am_search:'Hledat', am_scan:'Kód', am_photo:'Foto', am_describe:'Popsat', am_recipe:'Recept', am_manual:'Ručně',
  am_per100:'Na 100 g', am_grams:'Gramy', am_need_g:'Zadejte množství v gramech.',
  fs_ph:'Např. kuřecí prsa, ovesné vločky, banán', fs_hint:'Pište česky nebo anglicky. Hledá se ve vašich potravinách a v databázi zhruba 3 800 základních potravin.',
  fs_recent:'Nedávno zapsané', fs_none:'Nic nenalezeno.', fs_off:'Hledat výrobky v Open Food Facts', fs_est:'Nechat odhadnout Claudem',
  fs_mine:'moje', fs_last:'naposledy {g} g',
  sc_hint:'Namiřte kameru na čárový kód.', sc_manual_ph:'Nebo opište číslo kódu', sc_lookup:'Vyhledat', sc_bad:'Tohle nevypadá jako čárový kód.',
  sc_notfound:'Kód {c} v Open Food Facts není.', sc_photo_label:'Vyfotit etiketu místo toho', sc_unsupported:'Tento prohlížeč neumí číst kódy kamerou. Číslo kódu můžete opsat.',
  sc_nocam:'Kamera se nespustila.',
  ds_label:'Co jste jedl?', ds_ph:'Např. dvě vejce na másle, rohlík, půl avokáda a kafe s mlékem', ds_go:'Odhadnout', ds_save_all:'Zapsat vše',
  mn_name:'Název', mn_opt:'nepovinné', mn_need:'Vyplňte aspoň název a kcal.', mn_save_food:'Uložit jako moji potravinu', mn_save_food_d:'Jen když zadáte i gramy; příště ji najdete ve vyhledávání.',
  mn_portion:'porce',
  lg_slot:'Jídlo dne', lg_date:'Den', lg_saved:'Zapsáno.', lg_deleted:'Smazáno.', lg_edit:'Upravit záznam', lg_again:'Zapsat znovu dnes',
  lg_all_nutrients:'Všechny živiny', lg_est:'odhad', lg_est_note:'Tento záznam je odhad; čísla berte jako přibližná.',
  rv_prev:'Předchozí období', rv_next:'Další období',
  lg_prev:'Předchozí den', lg_next:'Další den', lg_empty_slot:'Zatím nic.',
  lg_copy_prev:'Zkopírovat jídla z předchozího dne', lg_copy_none:'Předchozí den nic zapsáno není.', lg_copy_q:'Zkopírovat {n} záznamů z předchozího dne do tohoto dne?',
  nt_none:'Žádné údaje o živinách.', nt_more:'Vitaminy, minerály a další ({n})',
  conf_low:'nízká jistota', conf_medium:'střední jistota', conf_high:'vysoká jistota',
  diff_easy:'snadné', diff_medium:'střední', diff_hard:'náročné',

  sp_today:'Doplňky dnes', sp_manage:'Spravovat', sp_none:'Zatím žádné doplňky.', sp_none_long:'Zatím tu nejsou žádné doplňky. Přidejte vlastní nebo začněte předvolbou a upravte hodnoty podle etikety.',
  sp_presets:'Rychlé předvolby', sp_presets_note:'Předvolby jsou běžné dávky. Vždy je porovnejte s etiketou svého výrobku.',
  sp_ul_over:'Doplňky na tento den dávají dohromady {a} {u} (živina: {n}). Bezpečný horní limit EU z doplňků je {ul} {u} denně.',
  sp_new:'Nový doplněk', sp_edit:'Upravit doplněk', sp_name:'Název', sp_form:'Forma', sp_units:'Kusů na dávku', sp_unit_label:'Jednotka (nepovinné)', sp_unit_label_ph:'např. kapsle, odměrka 5 g',
  sp_per_unit:'Obsah jednoho kusu', sp_add_nut:'Živina', sp_iu:'Vitamin D v IU', sp_iu_q:'Kolik IU vitaminu D obsahuje jeden kus?',
  sp_extra:'Další látky (nepočítají se do živin)', sp_extra_ph:'např. Kreatin 5 g; Kurkumin 500 mg',
  sp_days:'Dny', sp_rep_days:'Vybrané dny', sp_rep_alt:'Obden', sp_rep_start:'První den',
  sp_time:'Kdy', sp_active:'Aktivní', sp_paused:'pozastaveno', sp_taken:'Zapsáno jako užité.', sp_untaken:'Zrušeno.',
  sp_form_capsule:'kapsle', sp_form_tablet:'tableta', sp_form_softgel:'gelová kapsle', sp_form_powder:'prášek', sp_form_drops:'kapky', sp_form_liquid:'tekutina',
  sp_time_morning:'ráno', sp_time_noon:'v poledne', sp_time_evening:'večer', sp_time_any:'kdykoli',

  rt_suggest:'Návrhy', rt_all:'Všechny recepty',
  rl_search_ph:'Hledat recept, surovinu nebo štítek', rl_fav:'Oblíbené', rl_tags:'Štítky', rl_count:'Zobrazeno {n} z {all}',
  rl_empty:'Zatím tu nejsou žádné recepty. Archiv z Instagramu se sem doplní po první noční extrakci.', rl_nomatch:'Tomuto filtru nic neodpovídá.',
  rl_new:'Napsat vlastní recept',
  tagns_meal:'Jídlo dne', tagns_prep:'Příprava', tagns_time:'Čas', tagns_diet:'Strava', tagns_ing:'Hlavní suroviny', tagns_cuisine:'Kuchyně',
  tagns_method:'Technika', tagns_equip:'Vybavení', tagns_flavor:'Chuť', tagns_course:'Chod', tagns_nutri:'Živiny',
  tag_meal_breakfast:'Snídaně', tag_meal_lunch:'Oběd', tag_meal_snack:'Svačina', tag_meal_dinner:'Večeře',
  tag_prep_meal_prep:'Meal prep', tag_prep_freezer_friendly:'Do mrazáku', tag_prep_one_pot:'Jeden hrnec', tag_prep_no_cook:'Bez vaření',
  tag_time_under_15:'Do 15 min', tag_time_under_30:'Do 30 min', tag_time_under_60:'Do hodiny', tag_time_over_60:'Přes hodinu',
  tag_diet_high_protein:'Hodně bílkovin', tag_diet_vegetarian:'Vegetariánské', tag_diet_vegan:'Veganské', tag_diet_low_carb:'Méně sacharidů',
  tag_diet_high_fibre:'Hodně vlákniny', tag_diet_gluten_free:'Bez lepku', tag_diet_dairy_free:'Bez mléčných výrobků',
  orig_archive:'Archiv', orig_starter:'Startovní', orig_claude:'Od Clauda', orig_own:'Vlastní',
  rc_missing:'Recept nebyl nalezen.', rc_excluded:'obsahuje vyloučené', rc_excl_h:'Pozor, obsahuje vaše vyloučené:',
  rc_time:'Čas', rc_prep_cook:'příprava {p}, vaření {c} min', rc_kcal_serv:'kcal na porci', rc_difficulty:'Náročnost',
  rc_log:'Zapsat porci', rc_fav:'Oblíbený', rc_missing_btn:'Co mi chybí?', rc_ask:'Zeptat se Clauda',
  rc_ingredients:'Suroviny', rc_serv_short:'porce', rc_servings:'Porce', rc_servings_n:'{n} porce', rc_servings_eaten:'Kolik porcí',
  rc_optional:'nepovinné', rc_steps:'Postup', rc_var_tips:'Varianty a tipy', rc_storage:'Skladování a meal prep',
  rc_fridge:'V lednici', rc_freezer:'Do mrazáku', rc_days:'{n} dny',
  rc_nutrition:'Živiny na porci', rc_nut_basis_estimated:'Odhad ze surovin', rc_nut_basis_stated:'Hodnoty uvedené autorem receptu', rc_nut_basis_label:'Z etikety',
  rc_nut_basis_computed:'Spočítáno z databáze potravin', rc_nut_basis_none:'Živiny zatím nejsou spočítané',
  rc_no_nutrition:'Recept zatím nemá spočítané živiny, zapíše se jen název.', rc_stated:'Autor receptu uvádí na porci: {v}. Níže je výpočet z databáze potravin podle surovin.',
  rc_sources:'Zdroje', rc_caption:'Původní popisek', rc_video_drive:'video na Disku', rc_src_claude:'Navrhl Claude ({m})',
  rc_extracted:'Vytaženo {d}, {c}', rc_gaps:'Co v originále chybělo',
  rc_mynotes:'Moje poznámky', rc_mynotes_ph:'Co upravit příště, jak to chutnalo…', rc_cooked:'Vařeno {n}×, naposledy {d}',
  rc_delete:'Smazat recept', rc_missing_note:'Zaškrtnuté máte doma. Nezaškrtnuté se po uložení přidají do nákupního seznamu.',
  rc_missing_save:'Uložit do spíže a nákupu', rc_ask_seed:'K receptu „{t}“: ',
  or_title:'Název receptu', or_ing:'Suroviny, jedna na řádek', or_ing_ph:'200 g rýže\n2 lžíce sójové omáčky\n1 cibule',
  or_steps:'Postup, jeden krok na řádek', or_steps_ph:'Uvařte rýži.\nNa pánvi osmahněte cibuli.', or_note:'Živiny se zatím nepočítají; můžete se na ně zeptat Clauda v chatu.',
  or_need_title:'Vyplňte název.',
  sg_target:'cíl asi {k} kcal', sg_done:'Už zapsáno {k} kcal, tohle jsou nápady na příště.',sg_servings:'{n} porce ≈ {k} kcal', sg_none_slot:'Žádný recept se sem teď nehodí.',
  sg_noprofile:'Bez profilu se nedá odhadnout, kolik kcal na jídlo připadá. Návrhy jsou jen podle štítků.',
  sg_norecipes:'Zatím tu nejsou recepty. Návrhy od Clauda fungují i bez archivu.',
  sg_r_fits:'sedí na kalorie', sg_r_protein:'hodně bílkovin', sg_r_pantry:'většinu máte doma', sg_r_fav:'oblíbený',
  sg_ai_btn:'Nové nápady od Clauda', sg_ai_p:'Claude navrhne tři různé recepty na {slot} podle profilu, toho, co jste dnes snědl, a spíže.',
  sg_ai_extra:'Přání (nepovinné)', sg_ai_extra_ph:'např. něco s čočkou, bez trouby, do 20 minut', sg_ai_go:'Navrhnout', sg_ai_again:'Navrhnout jiné',
  sg_show_full:'Celý recept', sg_save:'Uložit do receptů', sg_saved:'Uloženo',
  sg_prep_h:'Meal prep', sg_prep_p:'Tři recepty na vaření dopředu: vydrží 3 až 4 dny v lednici a dobře se ohřívají.', sg_prep_btn:'Navrhnout meal prep',

  ph_title:'Vyhodnotit fotku', ph_intro:'Jídlo na talíři, výrobek nebo tabulka nutričních hodnot. Claude přečte, co vidí, a porovná to s vaším profilem a dneškem.',
  ph_h_auto:'Poznat samo', ph_h_dish:'Jídlo', ph_h_nutrition_label:'Etiketa', ph_h_packaged_product:'Výrobek',
  ph_take:'Vyfotit', ph_upload:'Z galerie', ph_note:'Poznámka (nepovinné)', ph_note_ph:'např. snědl jsem polovinu', ph_go:'Vyhodnotit', ph_again:'Vyhodnotit znovu',
  ph_bad:'Obrázek se nepodařilo načíst.', ph_working:'Claude se dívá na fotku, obvykle to trvá 5 až 20 sekund.',
  ph_basis_read_from_label:'Hodnoty přečtené z etikety', ph_basis_estimated_from_photo:'Odhad z fotky', ph_basis_typical_values:'Typické hodnoty',
  ph_why:'Proč', ph_tweaks:'Co upravit', ph_portion:'Zapsat', ph_log:'Zapsat do deníku', ph_save_food:'Uložit jako moji potravinu',
  ph_no100:'Chybí hodnoty na 100 g.', ph_local_check:'kontrola v telefonu', ph_chat_seed:'K fotce „{name}“ ({verdict}): ',

  pt_h:'Spíž', pt_shop_h:'Nákupní seznam', pt_chip:'Spíž: {n}', pt_shop_chip:'Nákup: {n}',
  pt_note:'Co máte doma. Claude s tím počítá v návrzích i v chatu a umí seznam sám upravit, když mu napíšete, co jste koupil nebo co došlo.',
  pt_shop_note:'Co došlo nebo chybí do receptů.', pt_add_ph:'Např. vejce, rýže, špenát (víc najednou oddělte čárkou)',
  pt_empty:'Spíž je prázdná.', pt_shop_empty:'Nákupní seznam je prázdný.', pt_have:'mám', pt_buy:'koupit', pt_need:'chybí',
  pt_copy:'Kopírovat seznam', pt_bought_all:'Všechno koupeno', pt_updated:'Spíž a nákup upraveny.',
  ch_new:'Nový chat', ch_ph:'Napište zprávu…', ch_send:'Poslat',
  ch_empty:'Zeptejte se, co uvařit z toho, co máte doma, co chybí do receptu, nebo jak naplánovat meal prep.',
  ch_q1:'Co uvařím z toho, co mám doma?', ch_q2:'Co mi chybí na meal prep na 3 dny?', ch_q3:'Čím dnes doplním bílkoviny?', ch_q4:'Jakou zeleninu koupit tento týden?',
  ch_pantry_done:'Spíž upravena: {list}', ch_recipe_saved:'Recept uložen: {t}',

  rv_week:'Týden', rv_month:'Měsíc', rv_empty:'Za toto období není nic zapsáno.',
  rv_logged:'Zapsáno {n} z {m} dní', rv_avg_kcal:'Průměr energie', rv_few_days:'Zapsaných dní je málo, závěry berte opatrně.',
  rv_chart:'Energie po dnech', rv_flags:'Co vyčnívá', rv_all_ok:'Nic výrazně nechybí ani nepřebývá, pokud jsou data úplná.',
  rv_lacking:'Chybí', rv_high:'Přebývá', rv_nodata:'Nedá se posoudit, málo údajů: {list}.',
  rv_add_h:'Co přidat', rv_add_per100:'nejvíc na 100 kcal', rv_add_note:'Potraviny z databáze bez vašich vyloučených, recepty z archivu. Hodnoty v závorce jsou na 100 g.',
  rv_reduce_h:'Co ubrat', rv_per_day:'denně', rv_all:'Všechny živiny', rv_cov:'data pro {p} % energie',
  rv_st_ok:'v pořádku', rv_st_low:'chybí', rv_st_low2:'výrazně chybí', rv_st_close:'skoro', rv_st_high:'přes limit', rv_st_near:'blízko limitu',
  rv_st_nodata:'málo údajů', rv_st_info:'jen pro informaci',
  rv_ref_note:'Referenční hodnoty: EFSA (Evropský úřad pro bezpečnost potravin) pro dospělé, nasycené tuky podle WHO. Průměr je za dny se zápisem.',
  rv_incl_supp:'Započítat doplňky stravy', rv_ai_h:'Rozbor od Clauda', rv_ai_p:'Claude dostane spočítaná čísla za období (ne celý deník) a napíše konkrétní doporučení.',
  rv_ai_btn:'Napsat rozbor', rv_ai_again:'Napsat znovu', rv_ai_when:'Napsáno {d}',

  pg_h:'Cíle stravy', pg_intro:'Podle tohoto se řídí návrhy jídel, chat i rozbory.',
  pg_style:'Styl stravy', pg_aims:'O co mi jde', pg_focus:'Na které živiny se zaměřit', pg_notes:'Poznámky pro Clauda',
  pg_notes_ph:'Vlastními slovy: co vám dělá dobře a co ne, čemu se vyhýbáte, co chcete změnit.',
  slp_intro:'Vyberte vzorec, nebo nastavte vlastní procenta níže.',
  slp_three:'3 jídla',
  slp_snack:'3 jídla a svačina',
  slp_bigbf:'Velká snídaně, lehká večeře',
  slp_lightbf:'Lehká snídaně, hlavní jídlo později',
  fp_everything:'Jím všechno', fp_littlemeat:'Málo masa', fp_pescatarian:'Ryby ano, maso ne', fp_vegetarian:'Vegetariánská', fp_vegan:'Veganská', fp_carnivore:'Jen živočišná strava', fc_coeliac:'Celiakie', fc_lactose:'Nesnášenlivost laktózy', fc_kidney:'Onemocnění ledvin', fr_halal:'Halal', fr_kosher:'Košer', fr_nopork:'Bez vepřového', fr_nobeef:'Bez hovězího', fr_noalcohol:'Bez alkoholu',
  pw_h:'Co jíte', pw_intro:'Jedna volba. Vegetariánská a veganská navíc vyřadí maso a ryby (veganská i vejce, mléčné výrobky a med) z návrhů, receptů i chatu.',
  fp_everything_d:'Nic se nevyřazuje.', fp_littlemeat_d:'Maso jen občas. Nic se neskrývá, Claude drží maso střídmě.', fp_pescatarian_d:'Ryby a mořské plody, maso ne.',
  fp_vegetarian_d:'Bez masa a ryb. Vejce a mléčné výrobky ano, pokud je níže nevyškrtnete.', fp_vegan_d:'Bez živočišných potravin: bez masa, ryb, vajec, mléčných výrobků a medu.', fp_carnivore_d:'Jen živočišné potraviny.',
  fpo_noeggs:'Bez vajec', fpo_nomilk:'Bez mléčných výrobků',
  fp_carnivore_warn:'Strava jen z živočišných potravin má málo dlouhodobých studií. Lidem, kteří tak jedí, často stoupá LDL cholesterol a bez rostlin má strava velmi málo vlákniny a vitaminu C a často chybí vápník, hořčík, thiamin, folát a jód. Pokud ji zvolíte, nechte si u lékaře zkontrolovat cholesterol a v Přehledu sledujte, co chybí. Aplikace pro tuto volbu rostlinné potraviny neskrývá.',
  fc_h:'Zdravotní stav', fc_note_coeliac:'Celiakie skryje vše s lepkem, stejně jako alergie na lepek.',
  fc_note_lactose:'Alergie na mléko není totéž co nesnášenlivost laktózy. Většina lidí s nesnášenlivostí laktózy snese najednou asi 12 g laktózy (zhruba sklenici mléka), proto se mléčné výrobky neskrývají; Claude drží menší porce nebo volí bezlaktózové výrobky.',
  fc_note_kidney:'Při onemocnění ledvin potřebují cíle bílkovin radu lékaře; Claude o tom ví.',
  fr_h:'Pravidla stravy', fr_note:'Skryjí vepřové, hovězí, alkohol nebo mořské plody v surovinách. Certifikaci halal a košer ze seznamu surovin ověřit nelze.',
  ft_summary:'Doladit: zdravotní zaměření, preference, poznámky', ft_focus:'Zdravotní zaměření', ft_hints:'Bylo by fajn', ft_prefs:'Preference',
  pf_avoidgluten:'Vyhýbám se lepku dobrovolně', pf_lactosefreeproducts:'Raději bezlaktózové výrobky', pm_h:'Jídla během dne',
  p_optional:'nepovinné', p_bf:'Tělesný tuk % (nepovinné)', p_bf_note:'Pokud ho znáte (třeba z váhy s měřením složení těla), aplikace použije rovnici podle netukové hmoty, která pohlaví nepotřebuje.',
  p_periods:'Máte menstruaci?', p_periods_yes:'Ano', p_periods_no:'Ne', p_periods_skip:'Nechci uvádět', p_periods_note:'Slouží jen pro cíl železa: 16 mg denně s menstruací, 11 mg bez ní. Nechci uvádět počítá s 16 mg.',
  p_energy_note:'Odhad kalorií používá váhu, věk a výšku (nebo tělesný tuk), bez nastavení pohlaví: bere střed mužské a ženské varianty rovnice a ukazuje rozpětí. Až budete pár týdnů zapisovat jídlo a váhu, aplikace ho upraví podle vašich vlastních čísel.',
  pg_slots:'Rozdělení dne mezi jídla', pg_slots_note:'Procenta denní energie. Nemusí dávat přesně 100, přepočítají se.',
  ms_preview:'Při středu vašeho cíle {kcal} kcal: bílkoviny asi {p} g ({pkg} g na kg váhy), tuky {f} g, sacharidy {c} g denně.',
  ms_fat_high:'Tuky nad 35 % energie jsou mimo referenční rozmezí EU (20 až 35 %).',
  ms_prot_high:'To je víc bílkovin, než většina lidí využije: i pro nabírání svalů stačí zhruba 1,6 až 2,2 g na kg.',
  slot_preview:'Při {kcal} kcal denně: {list}. Určuje jen velikost návrhů jídel, denní cíl nemění.',
  ds_omnivore:'Jím všechno', ds_flexitarian:'Málo masa', ds_pescatarian:'Ryby ano, maso ne', ds_vegetarian:'Vegetariánská', ds_vegan:'Veganská',
  ds_mediterranean:'Středomořská', ds_lowcarb:'Méně sacharidů', ds_highprotein:'Hodně bílkovin', ds_glutenfree:'Bez lepku', ds_lactosefree:'Bez laktózy',
  aim_muscle:'Nabrat svaly', aim_fatloss:'Zhubnout tuk', aim_energy:'Víc energie přes den', aim_digestion:'Lepší trávení', aim_fibre:'Víc vlákniny',
  aim_lesssugar:'Míň cukru', aim_lesssalt:'Míň soli', aim_veg:'Víc zeleniny', aim_protein:'Víc bílkovin', aim_heart:'Zdravé srdce', aim_sleep:'Lepší spánek', aim_skin:'Pleť',
  pf_dislikes:'Co nemám rád (měkké, jen se tomu vyhnout)', pf_dislikes_ph:'např. koriandr, olivy',
  pk_prep:'Meal prep', pk_days:'Kolik dní v týdnu vařím', pk_batch:'Porcí najednou',

  k_anthropic_tip:'Doporučení: vytvořte pro NutriLog samostatný klíč a v konzoli Anthropic mu nastavte měsíční limit útraty.',
  bud_label:'Měsíční rozpočet na Clauda v USD (0 = bez hlídání)', bud_month:'Tento měsíc utraceno', bud_note:'Po překročení se aplikace před každým voláním zeptá. Útrata je odhad z počtu tokenů a cen níže.',
  arch_h:'Archiv receptů', arch_intro:'Recepty vytažené z vašich uložených reelů. Hlavní kopie je na Google Disku, aplikace si je stahuje z datového repozitáře na GitHubu (stejného jako záloha).',
  arch_last:'Poslední synchronizace', arch_path:'Složka archivu v repozitáři', arch_sync:'Synchronizovat', arch_import:'Načíst ze souboru',
  arch_starter:'Ukazovat startovní recepty', arch_starter_d:'Tucet receptů od Clauda, aby návrhy fungovaly už před prvním archivem.',
  arch_need_repo:'Nejdřív vyplňte GitHub token a repozitář.', arch_none_yet:'Archiv v repozitáři zatím není.', arch_same:'Archiv je aktuální.',
  arch_synced:'Archiv načten, receptů: {n}.', arch_bad_file:'Tento soubor nevypadá jako archiv receptů.',
  b_format_note:'Formát zálohy je popsaný v souboru docs/DATA_FORMAT.md v repozitáři aplikace, aby ji mohly číst i další aplikace.',
  about_fooddb:'Databáze potravin',
  off_credit:'Údaje o výrobcích z Open Food Facts ({link}), licence ODbL.',
  about_products:'Údaje o výrobcích',
  dg_fooddb:'Databáze potravin', dg_fooddb_ok:'načtena, {n} potravin', dg_fooddb_no:'zatím nenačtena',
  ai_nokey_h:'Chybí klíč k Claudovi', ai_nokey_p:'Tahle funkce potřebuje klíč k API Anthropic. Vložte ho v Nastavení, v části Klíče k API.',
  ai_budget_h:'Měsíční rozpočet je vyčerpaný', ai_budget_p:'Tento měsíc je utraceno asi {spent} USD z rozpočtu {lim} USD. Pokračovat i tak?', ai_budget_go:'Pokračovat',
  ai_working:'Pracuji…', ai_working_long:'Claude píše recepty, trvá to obvykle 20 až 60 sekund.', ai_bad_reply:'Claude odpověděl v nečekaném tvaru. Zkuste to znovu.'
});
Object.assign(STR.en, {
  mac_p:'P', mac_f:'F', mac_c:'C',
  today:'Today', db_blocked:'The app is open in another tab. Close it so this one can update.',
  slot_breakfast:'Breakfast', slot_lunch:'Lunch', slot_snack:'Snack', slot_dinner:'Dinner', slot_other:'Other',
  nut_fib:'Fibre',
  td_eaten:'Eaten today', td_range:'Target {a} to {b} kcal', td_left:'{a} to {b} kcal to go', td_inrange:'in range, {b} kcal to spare', td_over:'{n} kcal over the top of the range',
  td_meals:'Meals', td_add:'add', td_next:'Ideas for {slot}', td_more:'More ideas',
  fab_supp:'Supplements',
  add_title:'Add: {slot}',
  am_search:'Search', am_scan:'Barcode', am_photo:'Photo', am_describe:'Describe', am_recipe:'Recipe', am_manual:'Manual',
  am_per100:'Per 100 g', am_grams:'Grams', am_need_g:'Enter the amount in grams.',
  fs_ph:'e.g. chicken breast, oats, banana', fs_hint:'Type in Czech or English. Searches your own foods and a database of about 3,800 basic foods.',
  fs_recent:'Recently logged', fs_none:'Nothing found.', fs_off:'Search products on Open Food Facts', fs_est:'Let Claude estimate it',
  fs_mine:'mine', fs_last:'last {g} g',
  sc_hint:'Point the camera at the barcode.', sc_manual_ph:'Or type the barcode number', sc_lookup:'Look up', sc_bad:'That does not look like a barcode.',
  sc_notfound:'Barcode {c} is not on Open Food Facts.', sc_photo_label:'Photograph the label instead', sc_unsupported:'This browser cannot read barcodes with the camera. You can type the number.',
  sc_nocam:'The camera did not start.',
  ds_label:'What did you eat?', ds_ph:'e.g. two eggs fried in butter, a bread roll, half an avocado and coffee with milk', ds_go:'Estimate', ds_save_all:'Log all',
  mn_name:'Name', mn_opt:'optional', mn_need:'Fill in at least the name and kcal.', mn_save_food:'Save as my food', mn_save_food_d:'Only if you enter grams too; next time it shows up in search.',
  mn_portion:'portion',
  lg_slot:'Meal', lg_date:'Day', lg_saved:'Logged.', lg_deleted:'Deleted.', lg_edit:'Edit entry', lg_again:'Log again today',
  lg_all_nutrients:'All nutrients', lg_est:'estimate', lg_est_note:'This entry is an estimate; treat the numbers as approximate.',
  rv_prev:'Previous period', rv_next:'Next period',
  lg_prev:'Previous day', lg_next:'Next day', lg_empty_slot:'Nothing yet.',
  lg_copy_prev:'Copy meals from the previous day', lg_copy_none:'Nothing was logged the previous day.', lg_copy_q:'Copy {n} entries from the previous day into this day?',
  nt_none:'No nutrient data.', nt_more:'Vitamins, minerals and more ({n})',
  conf_low:'low confidence', conf_medium:'medium confidence', conf_high:'high confidence',
  diff_easy:'easy', diff_medium:'medium', diff_hard:'hard',

  sp_today:'Supplements today', sp_manage:'Manage', sp_none:'No supplements yet.', sp_none_long:'No supplements yet. Add your own or start from a preset and adjust the values to your label.',
  sp_presets:'Quick presets', sp_presets_note:'Presets are common doses. Always check them against your product label.',
  sp_ul_over:'Your supplements for this day add up to {a} {u} of {n}. The EU safe upper level from supplements is {ul} {u} a day.',
  sp_new:'New supplement', sp_edit:'Edit supplement', sp_name:'Name', sp_form:'Form', sp_units:'Units per dose', sp_unit_label:'Unit (optional)', sp_unit_label_ph:'e.g. capsule, 5 g scoop',
  sp_per_unit:'Contents of one unit', sp_add_nut:'Nutrient', sp_iu:'Vitamin D in IU', sp_iu_q:'How many IU of vitamin D in one unit?',
  sp_extra:'Other substances (not counted as nutrients)', sp_extra_ph:'e.g. Creatine 5 g; Curcumin 500 mg',
  sp_days:'Days', sp_rep_days:'Chosen days', sp_rep_alt:'Every other day', sp_rep_start:'First day',
  sp_time:'When', sp_active:'Active', sp_paused:'paused', sp_taken:'Logged as taken.', sp_untaken:'Removed.',
  sp_form_capsule:'capsule', sp_form_tablet:'tablet', sp_form_softgel:'softgel', sp_form_powder:'powder', sp_form_drops:'drops', sp_form_liquid:'liquid',
  sp_time_morning:'morning', sp_time_noon:'midday', sp_time_evening:'evening', sp_time_any:'any time',

  rt_suggest:'Suggestions', rt_all:'All recipes',
  rl_search_ph:'Search a recipe, ingredient or tag', rl_fav:'Favourites', rl_tags:'Tags', rl_count:'Showing {n} of {all}',
  rl_empty:'No recipes yet. The Instagram archive arrives here after the first overnight extraction.', rl_nomatch:'Nothing matches this filter.',
  rl_new:'Write my own recipe',
  tagns_meal:'Meal', tagns_prep:'Prep', tagns_time:'Time', tagns_diet:'Diet', tagns_ing:'Main ingredients', tagns_cuisine:'Cuisine',
  tagns_method:'Technique', tagns_equip:'Equipment', tagns_flavor:'Flavour', tagns_course:'Course', tagns_nutri:'Nutrients',
  tag_meal_breakfast:'Breakfast', tag_meal_lunch:'Lunch', tag_meal_snack:'Snack', tag_meal_dinner:'Dinner',
  tag_prep_meal_prep:'Meal prep', tag_prep_freezer_friendly:'Freezer friendly', tag_prep_one_pot:'One pot', tag_prep_no_cook:'No cook',
  tag_time_under_15:'Under 15 min', tag_time_under_30:'Under 30 min', tag_time_under_60:'Under an hour', tag_time_over_60:'Over an hour',
  tag_diet_high_protein:'High protein', tag_diet_vegetarian:'Vegetarian', tag_diet_vegan:'Vegan', tag_diet_low_carb:'Low carb',
  tag_diet_high_fibre:'High fibre', tag_diet_gluten_free:'Gluten free', tag_diet_dairy_free:'Dairy free',
  orig_archive:'Archive', orig_starter:'Starter', orig_claude:'From Claude', orig_own:'Own',
  rc_missing:'Recipe not found.', rc_excluded:'contains excluded', rc_excl_h:'Careful, contains your exclusions:',
  rc_time:'Time', rc_prep_cook:'prep {p}, cook {c} min', rc_kcal_serv:'kcal per serving', rc_difficulty:'Difficulty',
  rc_log:'Log a serving', rc_fav:'Favourite', rc_missing_btn:'What am I missing?', rc_ask:'Ask Claude',
  rc_ingredients:'Ingredients', rc_serv_short:'servings', rc_servings:'Servings', rc_servings_n:'{n} servings', rc_servings_eaten:'How many servings',
  rc_optional:'optional', rc_steps:'Method', rc_var_tips:'Variations and tips', rc_storage:'Storage and meal prep',
  rc_fridge:'In the fridge', rc_freezer:'Freezes', rc_days:'{n} days',
  rc_nutrition:'Nutrients per serving', rc_nut_basis_estimated:'Estimated from ingredients', rc_nut_basis_stated:'Values stated by the recipe author', rc_nut_basis_label:'From a label',
  rc_nut_basis_computed:'Computed from the food database', rc_nut_basis_none:'Nutrients not computed yet',
  rc_no_nutrition:'This recipe has no nutrients yet; only the name will be logged.', rc_stated:'The recipe author states per serving: {v}. Below is the calculation from the food database by ingredients.',
  rc_sources:'Sources', rc_caption:'Original caption', rc_video_drive:'video on Drive', rc_src_claude:'Suggested by Claude ({m})',
  rc_extracted:'Extracted {d}, {c}', rc_gaps:'Missing in the original',
  rc_mynotes:'My notes', rc_mynotes_ph:'What to change next time, how it tasted…', rc_cooked:'Cooked {n} times, last on {d}',
  rc_delete:'Delete recipe', rc_missing_note:'Ticked items are at home. Unticked ones go on the shopping list when you save.',
  rc_missing_save:'Save to pantry and shopping list', rc_ask_seed:'About the recipe "{t}": ',
  or_title:'Recipe name', or_ing:'Ingredients, one per line', or_ing_ph:'200 g rice\n2 tbsp soy sauce\n1 onion',
  or_steps:'Method, one step per line', or_steps_ph:'Cook the rice.\nFry the onion in a pan.', or_note:'Nutrients are not computed yet; you can ask Claude in the chat.',
  or_need_title:'Fill in the name.',
  sg_target:'target about {k} kcal', sg_done:'{k} kcal already logged; these are ideas for next time.',sg_servings:'{n} servings ≈ {k} kcal', sg_none_slot:'No recipe fits here right now.',
  sg_noprofile:'Without a profile the app cannot tell how many kcal a meal should have. Suggestions go by tags only.',
  sg_norecipes:'No recipes yet. Suggestions from Claude work without the archive.',
  sg_r_fits:'fits the kcal', sg_r_protein:'high protein', sg_r_pantry:'you have most of it', sg_r_fav:'favourite',
  sg_ai_btn:'New ideas from Claude', sg_ai_p:'Claude suggests three different {slot} recipes based on your profile, what you ate today and your pantry.',
  sg_ai_extra:'Wishes (optional)', sg_ai_extra_ph:'e.g. something with lentils, no oven, under 20 minutes', sg_ai_go:'Suggest', sg_ai_again:'Suggest others',
  sg_show_full:'Full recipe', sg_save:'Save to recipes', sg_saved:'Saved',
  sg_prep_h:'Meal prep', sg_prep_p:'Three recipes to cook ahead: they keep 3 to 4 days in the fridge and reheat well.', sg_prep_btn:'Suggest meal prep',

  ph_title:'Evaluate a photo', ph_intro:'A plate of food, a product or a nutrition table. Claude reads what it sees and compares it with your profile and today.',
  ph_h_auto:'Detect', ph_h_dish:'Meal', ph_h_nutrition_label:'Label', ph_h_packaged_product:'Product',
  ph_take:'Take a photo', ph_upload:'From gallery', ph_note:'Note (optional)', ph_note_ph:'e.g. I ate half of it', ph_go:'Evaluate', ph_again:'Evaluate again',
  ph_bad:'The image could not be read.', ph_working:'Claude is looking at the photo; this usually takes 5 to 20 seconds.',
  ph_basis_read_from_label:'Values read from the label', ph_basis_estimated_from_photo:'Estimated from the photo', ph_basis_typical_values:'Typical values',
  ph_why:'Why', ph_tweaks:'What to change', ph_portion:'Log it', ph_log:'Log to diary', ph_save_food:'Save as my food',
  ph_no100:'Values per 100 g are missing.', ph_local_check:'checked on the phone', ph_chat_seed:'About the photo "{name}" ({verdict}): ',

  pt_h:'Pantry', pt_shop_h:'Shopping list', pt_chip:'Pantry: {n}', pt_shop_chip:'To buy: {n}',
  pt_note:'What you have at home. Claude uses it for suggestions and in the chat, and updates it when you tell it what you bought or ran out of.',
  pt_shop_note:'What ran out or is missing for recipes.', pt_add_ph:'e.g. eggs, rice, spinach (separate several with commas)',
  pt_empty:'The pantry is empty.', pt_shop_empty:'The shopping list is empty.', pt_have:'have', pt_buy:'buy', pt_need:'missing',
  pt_copy:'Copy list', pt_bought_all:'Bought everything', pt_updated:'Pantry and shopping list updated.',
  ch_new:'New chat', ch_ph:'Write a message…', ch_send:'Send',
  ch_empty:'Ask what to cook from what you have, what a recipe is missing, or how to plan meal prep.',
  ch_q1:'What can I cook from what I have?', ch_q2:'What do I need for 3 days of meal prep?', ch_q3:'How do I top up protein today?', ch_q4:'Which vegetables should I buy this week?',
  ch_pantry_done:'Pantry updated: {list}', ch_recipe_saved:'Recipe saved: {t}',

  rv_week:'Week', rv_month:'Month', rv_empty:'Nothing is logged for this period.',
  rv_logged:'{n} of {m} days logged', rv_avg_kcal:'Average energy', rv_few_days:'Few days are logged; take the conclusions with care.',
  rv_chart:'Energy by day', rv_flags:'What stands out', rv_all_ok:'Nothing is clearly lacking or in excess, as far as the data is complete.',
  rv_lacking:'Lacking', rv_high:'Too much', rv_nodata:'Cannot judge, too little data: {list}.',
  rv_add_h:'What to add', rv_add_per100:'most per 100 kcal', rv_add_note:'Foods from the database without your exclusions, recipes from the archive. Values in brackets are per 100 g.',
  rv_reduce_h:'What to cut back', rv_per_day:'per day', rv_all:'All nutrients', rv_cov:'data for {p} % of energy',
  rv_st_ok:'fine', rv_st_low:'lacking', rv_st_low2:'clearly lacking', rv_st_close:'nearly there', rv_st_high:'over the limit', rv_st_near:'near the limit',
  rv_st_nodata:'too little data', rv_st_info:'for information',
  rv_ref_note:'Reference values: EFSA (European Food Safety Authority) for adults, saturated fat per WHO. Averages are over days with entries.',
  rv_incl_supp:'Count supplements', rv_ai_h:'Review by Claude', rv_ai_p:'Claude receives the computed numbers for the period (not the whole diary) and writes concrete advice.',
  rv_ai_btn:'Write a review', rv_ai_again:'Write again', rv_ai_when:'Written {d}',

  pg_h:'Diet goals', pg_intro:'Meal suggestions, the chat and the reviews follow this.',
  pg_style:'Diet style', pg_aims:'What I am after', pg_focus:'Nutrients to focus on', pg_notes:'Notes for Claude',
  pg_notes_ph:'In your own words: what works for you and what does not, what you avoid, what you want to change.',
  slp_intro:'Pick a pattern or set your own percentages below.',
  slp_three:'3 meals',
  slp_snack:'3 meals and a snack',
  slp_bigbf:'Big breakfast, light dinner',
  slp_lightbf:'Light breakfast, main meal later',
  fp_everything:'I eat everything', fp_littlemeat:'Little meat', fp_pescatarian:'Fish yes, meat no', fp_vegetarian:'Vegetarian', fp_vegan:'Vegan', fp_carnivore:'Animal foods only', fc_coeliac:'Coeliac disease', fc_lactose:'Lactose intolerance', fc_kidney:'Kidney disease', fr_halal:'Halal', fr_kosher:'Kosher', fr_nopork:'No pork', fr_nobeef:'No beef', fr_noalcohol:'No alcohol',
  pw_h:'What you eat', pw_intro:'One choice. Vegetarian and vegan also keep meat and fish (vegan: also eggs, milk products and honey) out of suggestions, recipes and the chat.',
  fp_everything_d:'No food groups left out.', fp_littlemeat_d:'Meat now and then. Nothing is hidden; Claude keeps meat modest.', fp_pescatarian_d:'Fish and seafood, no meat.',
  fp_vegetarian_d:'No meat or fish. Eggs and milk products are fine unless you tick them off below.', fp_vegan_d:'No animal foods: no meat, fish, eggs, milk products or honey.', fp_carnivore_d:'Only animal foods.',
  fpo_noeggs:'No eggs', fpo_nomilk:'No milk products',
  fp_carnivore_warn:'Eating only animal foods has few long-term studies. People who eat this way often see LDL cholesterol go up, and without plants the diet is very low in fibre and vitamin C and often short in calcium, magnesium, thiamin, folate and iodine. If you choose it, have your cholesterol checked by your doctor and use the Review to see what is missing. The app does not hide plant foods for this choice.',
  fc_h:'Health conditions', fc_note_coeliac:'Coeliac disease hides everything with gluten, the same as a gluten allergy.',
  fc_note_lactose:'Milk allergy is not the same as lactose intolerance. Most people with lactose intolerance handle up to about 12 g of lactose at a time (roughly a glass of milk), so milk products are not hidden; Claude keeps portions small or picks lactose-free products.',
  fc_note_kidney:'With kidney disease, protein targets need advice from your doctor; Claude is told about it.',
  fr_h:'Food rules', fr_note:'These hide pork, beef, alcohol or shellfish in ingredients. Halal and kosher certification cannot be checked from an ingredient list.',
  ft_summary:'Fine-tune: health focus, preferences, notes', ft_focus:'Health focus', ft_hints:'Also nice to have', ft_prefs:'Preferences',
  pf_avoidgluten:'Avoid gluten by choice', pf_lactosefreeproducts:'Prefer lactose-free products', pm_h:'Meals through the day',
  p_optional:'optional', p_bf:'Body fat % (optional)', p_bf_note:'If you know it (for example from a body composition scale), the app uses an equation based on lean mass that does not need sex.',
  p_periods:'Do you have periods?', p_periods_yes:'Yes', p_periods_no:'No', p_periods_skip:'Prefer not to say', p_periods_note:'Only used for the iron target: 16 mg a day with periods, 11 mg without. Prefer not to say uses 16 mg.',
  p_energy_note:'Your calorie estimate uses weight, age and height (or body fat) and no sex setting: it takes the midpoint of the male and female versions of the equation and shows the range. Once you log food and weight for a few weeks, the app corrects it from your own numbers.',
  pg_slots:'How the day splits between meals', pg_slots_note:'Percent of daily energy. They need not add up to exactly 100; they are rescaled.',
  ms_preview:'At the middle of your target, {kcal} kcal: protein about {p} g ({pkg} g per kg of body weight), fat {f} g, carbohydrate {c} g a day.',
  ms_fat_high:'Fat above 35 % of energy is outside the EU reference range (20 to 35 %).',
  ms_prot_high:'That is more protein than most people can use: about 1.6 to 2.2 g per kg is enough even for building muscle.',
  slot_preview:'At {kcal} kcal a day: {list}. This only sets the size of meal ideas; it does not change your daily target.',
  ds_omnivore:'I eat everything', ds_flexitarian:'Little meat', ds_pescatarian:'Fish yes, meat no', ds_vegetarian:'Vegetarian', ds_vegan:'Vegan',
  ds_mediterranean:'Mediterranean', ds_lowcarb:'Lower carb', ds_highprotein:'High protein', ds_glutenfree:'Gluten free', ds_lactosefree:'Lactose free',
  aim_muscle:'Build muscle', aim_fatloss:'Lose fat', aim_energy:'More energy through the day', aim_digestion:'Better digestion', aim_fibre:'More fibre',
  aim_lesssugar:'Less sugar', aim_lesssalt:'Less salt', aim_veg:'More vegetables', aim_protein:'More protein', aim_heart:'Heart health', aim_sleep:'Better sleep', aim_skin:'Skin',
  pf_dislikes:'Things I dislike (soft, just avoid)', pf_dislikes_ph:'e.g. coriander, olives',
  pk_prep:'Meal prep', pk_days:'Days a week I cook', pk_batch:'Servings per batch',

  k_anthropic_tip:'Tip: create a separate key for NutriLog and set a monthly spend limit for it in the Anthropic console.',
  bud_label:'Monthly budget for Claude in USD (0 = no check)', bud_month:'Spent this month', bud_note:'Once exceeded, the app asks before every call. Spend is estimated from token counts and the prices below.',
  arch_h:'Recipe archive', arch_intro:'Recipes extracted from your saved reels. The master copy is on Google Drive; the app downloads them from the GitHub data repository (the same one as the backup).',
  arch_last:'Last sync', arch_path:'Archive folder in the repository', arch_sync:'Sync', arch_import:'Load from a file',
  arch_starter:'Show starter recipes', arch_starter_d:'A dozen recipes from Claude so suggestions work before the first archive.',
  arch_need_repo:'Fill in the GitHub token and repository first.', arch_none_yet:'There is no archive in the repository yet.', arch_same:'The archive is up to date.',
  arch_synced:'Archive loaded: {n} recipes.', arch_bad_file:'This file does not look like a recipe archive.',
  b_format_note:'The backup format is described in docs/DATA_FORMAT.md in the app repository, so other apps can read it too.',
  about_fooddb:'Food database',
  off_credit:'Product data from Open Food Facts ({link}), ODbL licence.',
  about_products:'Product data',
  dg_fooddb:'Food database', dg_fooddb_ok:'loaded, {n} foods', dg_fooddb_no:'not loaded yet',
  ai_nokey_h:'Claude key missing', ai_nokey_p:'This needs an Anthropic API key. Paste it in Settings, under API keys.',
  ai_budget_h:'Monthly budget used up', ai_budget_p:'About {spent} USD of the {lim} USD budget is spent this month. Continue anyway?', ai_budget_go:'Continue',
  ai_working:'Working…', ai_working_long:'Claude is writing recipes; this usually takes 20 to 60 seconds.', ai_bad_reply:'Claude replied in an unexpected shape. Please try again.'
});

/* ---------- activity detail: daily life plus training ---------- */
Object.assign(STR.cs, {
  ad_toggle:'Popsat týden podrobně (běžný den a trénink zvlášť)',
  ad_note:'Jednoduché úrovně výše zahrnují trénink; tady se běžný den a trénink počítají zvlášť, takže vyberte úroveň běžného dne bez tréninku.',
  ad_base:'Běžný den bez tréninku',
  ad_b1:'Převážně sedím (méně než asi 5 000 kroků denně)', ad_b2:'Sedím, ale docela dost chodím', ad_b3:'Velkou část dne jsem na nohou', ad_b4:'Fyzicky náročná práce',
  ad_sessions:'Tréninků týdně', ad_minutes:'Minut na trénink', ad_type:'Hlavní druh tréninku',
  at_strength:'Silový trénink', at_heavy:'Těžké zvedání, vysoké úsilí', at_cycling:'Kolo, střední tempo', at_cyclinghard:'Kolo, ostře',
  at_circuits:'Kruhový trénink', at_hiit:'Intervalový trénink (HIIT)', at_climbing:'Lezení (bouldering nebo stěna)', at_yoga:'Jóga',
  ad_att:'Jak často plán opravdu dodržím', aa_always:'Skoro vždy', aa_usually:'Většinou', aa_sometimes:'Občas',
  ad_result:'Trénink přidá v průměru asi {kcal} kcal denně.'
});
Object.assign(STR.en, {
  ad_toggle:'Describe my week in detail (daily life and training separately)',
  ad_note:'The simple levels above include training; here daily life and training are counted separately, so pick the daily life level without training.',
  ad_base:'Daily life, without training',
  ad_b1:'Mostly sitting (under about 5,000 steps a day)', ad_b2:'Sitting, but I walk a fair bit', ad_b3:'On my feet much of the day', ad_b4:'Physically hard work',
  ad_sessions:'Training sessions a week', ad_minutes:'Minutes per session', ad_type:'Main kind of training',
  at_strength:'Strength training', at_heavy:'Heavy lifting, hard effort', at_cycling:'Cycling, moderate', at_cyclinghard:'Cycling, hard',
  at_circuits:'Circuit training', at_hiit:'Interval training (HIIT)', at_climbing:'Climbing (bouldering or wall)', at_yoga:'Yoga',
  ad_att:'How often the plan really happens', aa_always:'Almost always', aa_usually:'Usually', aa_sometimes:'Sometimes',
  ad_result:'Training adds about {kcal} kcal a day on average.'
});

/* ---------- looks ---------- */
Object.assign(STR.cs, { set_lookpick:'Vzhled' });
Object.assign(STR.en, { set_lookpick:'Look' });

/* ---------- sync ---------- */
Object.assign(STR.cs, {
  sy_title:'Synchronizace', sy_off:'Nepřipojeno. Data jsou jen v tomto zařízení.', sy_on:'Profil {name}, poslední synchronizace {when}',
  sy_offline:'Offline, synchronizace počká.', sy_err:'Synchronizace selhala: {msg}', sy_revoked:'Klíč už neplatí. Připojte se znovu odkazem.',
  sy_join:'Připojit se odkazem', sy_join_ph:'Vložte odkaz nebo klíč', sy_join_confirm:'Připojit se k profilu {name}?',
  sy_join_merge:'Data v tomto zařízení se přidají do profilu.', sy_join_switch:'Opustíte současný profil a data v zařízení se nahradí.',
  sy_leave:'Opustit profil', sy_leave_note:'Data zůstanou v zařízení i na serveru.', sy_now:'Synchronizovat teď',
  sy_url:'Adresa serveru', sy_advanced:'Pokročilé'
});
Object.assign(STR.en, {
  sy_title:'Sync', sy_off:'Not joined. Data lives on this device only.', sy_on:'Profile {name}, last sync {when}',
  sy_offline:'Offline, sync will wait.', sy_err:'Sync failed: {msg}', sy_revoked:'The key no longer works. Join again with a link.',
  sy_join:'Join with a link', sy_join_ph:'Paste the link or the key', sy_join_confirm:'Join the profile {name}?',
  sy_join_merge:'The data on this device will be added to the profile.', sy_join_switch:'You will leave the current profile and the data on this device will be replaced.',
  sy_leave:'Leave this profile', sy_leave_note:'Data stays on this device and on the server.', sy_now:'Sync now',
  sy_url:'Server address', sy_advanced:'Advanced'
});

/* ---------- invite links ---------- */
Object.assign(STR.cs, {
  sy_share:'Přidat další zařízení', sy_share_note:'Naskenujte kód nebo otevřete odkaz v druhém zařízení. Kdo má odkaz, má přístup k profilu.',
  sy_link_is_key:'Odkaz je klíč k profilu, posílejte ho jen soukromě.', sy_already:'Toto zařízení už je připojeno k tomuto profilu.'
});
Object.assign(STR.en, {
  sy_share:'Add another device', sy_share_note:'Scan the code or open the link on the other device. Anyone with the link has access to the profile.',
  sy_link_is_key:'The link is the key to the profile, send it privately only.', sy_already:'This device is already joined to this profile.'
});

/* ---------- quick mode ---------- */
Object.assign(STR.cs, {
  qm_title:'Rychl\u00fd re\u017eim', qm_note:'Jen z\u00e1pis j\u00eddla a dopl\u0148k na jedn\u00e9 obrazovce. Nastaven\u00ed tohoto za\u0159\u00edzen\u00ed.',
  qm_offer:'Mal\u00e1 obrazovka. Zapnout rychl\u00fd re\u017eim jen se z\u00e1pisem j\u00eddla?', qm_offer_yes:'Zapnout', qm_offer_no:'Nechat celou aplikaci',
  qm_shortcut:'Rychl\u00fd z\u00e1pis', qm_energy:'{kcal} z {lo} a\u017e {hi} kcal', qm_same:'Jako v\u010dera', qm_full:'Cel\u00e1 aplikace', t_quick:'Z\u00e1pis'
});
Object.assign(STR.en, {
  qm_title:'Quick mode', qm_note:'Only food and supplement logging on one screen. A setting of this device.',
  qm_offer:'Small screen. Turn on Quick mode with food logging only?', qm_offer_yes:'Turn on', qm_offer_no:'Keep the full app',
  qm_shortcut:'Quick log', qm_energy:'{kcal} of {lo} to {hi} kcal', qm_same:'Same as yesterday', qm_full:'Full app', t_quick:'Log'
});

/* ---------- texts without the assistant's name (Jan 2026-09-25) ---------- */
Object.assign(STR.cs, {
  fs_est:'Nechat odhadnout', orig_claude:'Návrh', rc_ask:'Zeptat se', rc_src_claude:'Návrh ({m})',
  or_note:'Živiny se zatím nepočítají; můžete se na ně zeptat v chatu.',
  sg_norecipes:'Zatím tu nejsou recepty. Nové nápady fungují i bez archivu.', sg_ai_btn:'Nové nápady',
  sg_ai_p:'Tři různé recepty na {slot} podle profilu, toho, co jste dnes snědl, a spíže.',
  ph_intro:'Jídlo na talíři, výrobek nebo tabulka nutričních hodnot. Fotka se přečte a porovná s vaším profilem a dneškem.',
  ph_working:'Prohlížím fotku, obvykle to trvá 5 až 20 sekund.',
  pt_note:'Co máte doma. Počítá se s tím v návrzích i v chatu a seznam se sám upraví, když napíšete, co jste koupil nebo co došlo.',
  rv_ai_h:'Rozbor', rv_ai_p:'Odešlou se jen spočítaná čísla za období (ne celý deník) a vrátí se konkrétní doporučení.',
  pg_notes:'Poznámky k návrhům', fp_littlemeat_d:'Maso jen občas. Nic se neskrývá, maso zůstává střídmé.',
  fc_note_lactose:'Alergie na mléko není totéž co nesnášenlivost laktózy. Většina lidí s nesnášenlivostí laktózy snese najednou asi 12 g laktózy (zhruba sklenici mléka), proto se mléčné výrobky neskrývají; návrhy drží menší porce nebo volí bezlaktózové výrobky.',
  fc_note_kidney:'Při onemocnění ledvin potřebují cíle bílkovin radu lékaře; návrhy s tím počítají.',
  bud_label:'Měsíční rozpočet v USD (0 = bez hlídání)', arch_starter_d:'Tucet úvodních receptů, aby návrhy fungovaly už před prvním archivem.',
  ai_nokey_h:'Chybí klíč', ai_working_long:'Píšu recepty, trvá to obvykle 20 až 60 sekund.', ai_bad_reply:'Odpověď přišla v nečekaném tvaru. Zkuste to znovu.'
});
Object.assign(STR.en, {
  fs_est:'Estimate it', orig_claude:'Suggested', rc_ask:'Ask', rc_src_claude:'Suggested ({m})',
  or_note:'Nutrients are not computed yet; you can ask in the chat.',
  sg_norecipes:'No recipes yet. New ideas work without the archive.', sg_ai_btn:'New ideas',
  sg_ai_p:'Three different {slot} recipes based on your profile, what you ate today and your pantry.',
  ph_intro:'A plate of food, a product or a nutrition table. The photo is read and compared with your profile and today.',
  ph_working:'Looking at the photo; this usually takes 5 to 20 seconds.',
  pt_note:'What you have at home. Used for suggestions and in the chat, and updated when you say what you bought or ran out of.',
  rv_ai_h:'Review', rv_ai_p:'Only the computed numbers for the period are sent (not the whole diary), and concrete advice comes back.',
  pg_notes:'Notes for suggestions', fp_littlemeat_d:'Meat now and then. Nothing is hidden; meat stays modest.',
  fc_note_lactose:'Milk allergy is not the same as lactose intolerance. Most people with lactose intolerance handle up to about 12 g of lactose at a time (roughly a glass of milk), so milk products are not hidden; suggestions keep portions small or pick lactose-free products.',
  fc_note_kidney:'With kidney disease, protein targets need advice from your doctor; suggestions take it into account.',
  bud_label:'Monthly budget in USD (0 = no check)', arch_starter_d:'A dozen starter recipes so suggestions work before the first archive.',
  ai_nokey_h:'Key missing', ai_working_long:'Writing recipes; this usually takes 20 to 60 seconds.', ai_bad_reply:'The reply came in an unexpected shape. Please try again.'
});
Object.assign(STR.cs, {
  ct_line:'Katalog receptů: {n}, aktualizováno {when}', ct_none:'Katalog receptů se zatím nestáhl.', ct_err:'Katalog se nepodařilo stáhnout: {msg}'
});
Object.assign(STR.en, {
  ct_line:'Recipe catalog: {n} recipes, updated {when}', ct_none:'The recipe catalog has not been downloaded yet.', ct_err:'Could not download the recipe catalog: {msg}'
});
Object.assign(STR.cs, {
  rs_add:'Poslat recept', rs_title:'Nový recept do katalogu', rs_link:'Odkaz na recept', rs_text:'Text receptu',
  rs_text_ph:'Vložte suroviny a postup, stačí i poznámky.', rs_help:'Stačí odkaz, text, nebo obojí. Claude recept převede do jednotné podoby a přidá ho do katalogu pro všechny.',
  rs_send:'Odeslat', rs_bad_link:'Odkaz musí začínat http:// nebo https://', rs_too_long:'Text je delší než 20 000 znaků.',
  rs_sent:'Recept odeslán. V katalogu se obvykle objeví do hodiny.', rs_offline:'Offline. Recept pošlete, až budete připojeni.',
  rs_limit:'Tento měsíc jste už poslali {n} receptů, víc nejde.', rs_err:'Odeslání selhalo: {msg}', rs_list_h:'Poslané recepty',
  rs_list_empty:'Zatím jste neposlali žádný recept.', rs_st_pending:'Zpracovává se', rs_st_published:'V katalogu',
  rs_st_merged:'Přidáno jako varianta receptu {title}', rs_st_duplicate:'V katalogu už je: {title}', rs_st_rejected:'Nepřidáno: {reason}',
  rs_r_not_recipe:'nevypadá to jako recept.', rs_r_unreadable:'odkaz nešel přečíst, vložte text receptu.', rs_r_invalid:'recept se nepodařilo převést.', rs_r_other:'neznámý důvod.'
});
Object.assign(STR.en, {
  rs_add:'Send a recipe', rs_title:'New recipe for the catalog', rs_link:'Link to the recipe', rs_text:'Recipe text',
  rs_text_ph:'Paste the ingredients and method; rough notes are fine.', rs_help:'A link, the text, or both. Claude converts the recipe to the common format and adds it to the catalog for everyone.',
  rs_send:'Send', rs_bad_link:'The link must start with http:// or https://', rs_too_long:'The text is longer than 20,000 characters.',
  rs_sent:'Recipe sent. It usually appears in the catalog within an hour.', rs_offline:'Offline. Send the recipe once you are connected.',
  rs_limit:'You have already sent {n} recipes this month, which is the limit.', rs_err:'Sending failed: {msg}', rs_list_h:'Recipes you sent',
  rs_list_empty:'You have not sent any recipes yet.', rs_st_pending:'Being processed', rs_st_published:'In the catalog',
  rs_st_merged:'Added as a variation of {title}', rs_st_duplicate:'Already in the catalog: {title}', rs_st_rejected:'Not added: {reason}',
  rs_r_not_recipe:'this does not look like a recipe.', rs_r_unreadable:'the link could not be read, paste the recipe text instead.', rs_r_invalid:'the recipe could not be converted.', rs_r_other:'unknown reason.'
});
Object.assign(STR.cs, {
  rc_to_taste:'dle chuti', rc_version:'Verze', ax_omnivore:'S masem', ax_pescatarian:'S rybami', ax_vegetarian:'Vegetariánská', ax_vegan:'Veganská',
  rc_flags_applied:'Upraveno: {list}', fl_gluten_free:'bez lepku', fl_lactose_free:'bez laktózy', fl_no:'bez: {a}',
  rc_axis_none:'Není pro vaši stravu', rc_axis_none_note:'Tento recept nemá verzi pro vaši stravu. Zobrazena je původní verze.',
  rc_nut_basis_stored:'Výživové hodnoty uložené s receptem'
});
Object.assign(STR.en, {
  rc_to_taste:'to taste', rc_version:'Version', ax_omnivore:'Omnivore', ax_pescatarian:'Pescatarian', ax_vegetarian:'Vegetarian', ax_vegan:'Vegan',
  rc_flags_applied:'Adjusted: {list}', fl_gluten_free:'gluten-free', fl_lactose_free:'lactose-free', fl_no:'without {a}',
  rc_axis_none:'Not for your diet', rc_axis_none_note:'This recipe has no version for your diet. The original version is shown.',
  rc_nut_basis_stored:'Nutrition as stored with the recipe'
});
Object.assign(STR.cs, {
  b_restore_merge_note:'Zařízení je připojené k profilu: po obnovení se data sloučí s profilem, novější záznam vyhrává.'
});
Object.assign(STR.en, {
  b_restore_merge_note:'This device is joined to a profile: after the restore the data is merged with the profile, the newer record wins.'
});
Object.assign(STR.cs, {
  tagns_dish:'Jídlo', tagns_budget:'Rozpočet', tagns_season:'Sezóna', tag_diet_high_fiber:'Hodně vlákniny',
  p_weight_short:'Váha', p_hint_height:'cm, nepovinné'
});
Object.assign(STR.en, {
  tagns_dish:'Dish', tagns_budget:'Budget', tagns_season:'Season', tag_diet_high_fiber:'High fibre',
  p_weight_short:'Weight', p_hint_height:'cm, optional'
});
Object.assign(STR.cs, {
  set_type:'Písmo', type_fraunces:'Fraunces a Figtree', type_marcellus:'Marcellus a Raleway', type_jost:'Jost', type_sample:'Aa 1 640 kcal'
});
Object.assign(STR.en, {
  set_type:'Type', type_fraunces:'Fraunces and Figtree', type_marcellus:'Marcellus and Raleway', type_jost:'Jost', type_sample:'Aa 1,640 kcal'
});
